-- Table structure for table `N_CHOKYO_SEISEKI`
-- Table structure for table `N_CHOKYO_SEISEKI`
--

DROP TABLE IF EXISTS `N_CHOKYO_SEISEKI`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `N_CHOKYO_SEISEKI` (
  `MakeDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=データ作成年月日; column=MakeDate; table=N_CHOKYO_SEISEKI; class=蓄積系; unit=yyyymmdd; doc=12-3-31-CHOKYO_SEISEKI; desc=西暦4桁+月日各2桁',
  `ChokyosiCode` varchar(5) NOT NULL COMMENT '[COL] name=調教師コード; column=ChokyosiCode; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; key=○',
  `Num` varchar(1) NOT NULL COMMENT '[COL] name=連番; column=Num; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; key=○; desc=成績連番',
  `SetYear` varchar(4) DEFAULT NULL COMMENT '[COL] name=設定年; column=SetYear; table=N_CHOKYO_SEISEKI; class=蓄積系; unit=yyyy; doc=12-3-31-CHOKYO_SEISEKI; desc=成績情報に設定されている年度',
  `HonSyokinHeichi` varchar(10) DEFAULT NULL COMMENT '[COL] name=平地本賞金合計; column=HonSyokinHeichi; table=N_CHOKYO_SEISEKI; class=蓄積系; unit=百円; doc=12-3-31-CHOKYO_SEISEKI; desc=中央の平地本賞金の合計',
  `HonSyokinSyogai` varchar(10) DEFAULT NULL COMMENT '[COL] name=障害本賞金合計; column=HonSyokinSyogai; table=N_CHOKYO_SEISEKI; class=蓄積系; unit=百円; doc=12-3-31-CHOKYO_SEISEKI; desc=中央の障害本賞金の合計',
  `FukaSyokinHeichi` varchar(10) DEFAULT NULL COMMENT '[COL] name=平地付加賞金合計; column=FukaSyokinHeichi; table=N_CHOKYO_SEISEKI; class=蓄積系; unit=百円; doc=12-3-31-CHOKYO_SEISEKI; desc=中央の平地付加賞金の合計',
  `FukaSyokinSyogai` varchar(10) DEFAULT NULL COMMENT '[COL] name=障害付加賞金合計; column=FukaSyokinSyogai; table=N_CHOKYO_SEISEKI; class=蓄積系; unit=百円; doc=12-3-31-CHOKYO_SEISEKI; desc=中央の障害付加賞金の合計',
  `HeichiChakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=平地着回数1; column=HeichiChakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `HeichiChakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=平地着回数2; column=HeichiChakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `HeichiChakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=平地着回数3; column=HeichiChakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `HeichiChakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=平地着回数4; column=HeichiChakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `HeichiChakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=平地着回数5; column=HeichiChakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `HeichiChakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=平地着回数6; column=HeichiChakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `SyogaiChakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=障害着回数1; column=SyogaiChakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `SyogaiChakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=障害着回数2; column=SyogaiChakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `SyogaiChakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=障害着回数3; column=SyogaiChakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `SyogaiChakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=障害着回数4; column=SyogaiChakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `SyogaiChakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=障害着回数5; column=SyogaiChakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `SyogaiChakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=障害着回数6; column=SyogaiChakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo1Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌平地着回数1; column=Jyo1Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo1Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌平地着回数2; column=Jyo1Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo1Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌平地着回数3; column=Jyo1Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo1Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌平地着回数4; column=Jyo1Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo1Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌平地着回数5; column=Jyo1Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo1Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌平地着回数6; column=Jyo1Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo2Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌障害着回数1; column=Jyo2Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo2Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌障害着回数2; column=Jyo2Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo2Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌障害着回数3; column=Jyo2Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo2Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌障害着回数4; column=Jyo2Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo2Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌障害着回数5; column=Jyo2Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo2Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=札幌障害着回数6; column=Jyo2Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo3Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館平地着回数1; column=Jyo3Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo3Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館平地着回数2; column=Jyo3Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo3Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館平地着回数3; column=Jyo3Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo3Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館平地着回数4; column=Jyo3Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo3Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館平地着回数5; column=Jyo3Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo3Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館平地着回数6; column=Jyo3Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo4Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館障害着回数1; column=Jyo4Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo4Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館障害着回数2; column=Jyo4Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo4Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館障害着回数3; column=Jyo4Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo4Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館障害着回数4; column=Jyo4Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo4Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館障害着回数5; column=Jyo4Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo4Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=函館障害着回数6; column=Jyo4Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo5Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島平地着回数1; column=Jyo5Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo5Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島平地着回数2; column=Jyo5Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo5Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島平地着回数3; column=Jyo5Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo5Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島平地着回数4; column=Jyo5Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo5Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島平地着回数5; column=Jyo5Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo5Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島平地着回数6; column=Jyo5Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo6Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島障害着回数1; column=Jyo6Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo6Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島障害着回数2; column=Jyo6Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo6Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島障害着回数3; column=Jyo6Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo6Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島障害着回数4; column=Jyo6Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo6Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島障害着回数5; column=Jyo6Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo6Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=福島障害着回数6; column=Jyo6Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo7Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟平地着回数1; column=Jyo7Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo7Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟平地着回数2; column=Jyo7Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo7Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟平地着回数3; column=Jyo7Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo7Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟平地着回数4; column=Jyo7Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo7Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟平地着回数5; column=Jyo7Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo7Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟平地着回数6; column=Jyo7Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo8Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟障害着回数1; column=Jyo8Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo8Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟障害着回数2; column=Jyo8Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo8Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟障害着回数3; column=Jyo8Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo8Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟障害着回数4; column=Jyo8Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo8Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟障害着回数5; column=Jyo8Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo8Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=新潟障害着回数6; column=Jyo8Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo9Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京平地着回数1; column=Jyo9Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo9Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京平地着回数2; column=Jyo9Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo9Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京平地着回数3; column=Jyo9Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo9Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京平地着回数4; column=Jyo9Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo9Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京平地着回数5; column=Jyo9Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo9Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京平地着回数6; column=Jyo9Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo10Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京障害着回数1; column=Jyo10Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo10Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京障害着回数2; column=Jyo10Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo10Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京障害着回数3; column=Jyo10Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo10Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京障害着回数4; column=Jyo10Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo10Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京障害着回数5; column=Jyo10Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo10Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=東京障害着回数6; column=Jyo10Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo11Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山平地着回数1; column=Jyo11Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo11Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山平地着回数2; column=Jyo11Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo11Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山平地着回数3; column=Jyo11Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo11Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山平地着回数4; column=Jyo11Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo11Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山平地着回数5; column=Jyo11Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo11Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山平地着回数6; column=Jyo11Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo12Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山障害着回数1; column=Jyo12Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo12Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山障害着回数2; column=Jyo12Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo12Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山障害着回数3; column=Jyo12Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo12Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山障害着回数4; column=Jyo12Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo12Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山障害着回数5; column=Jyo12Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo12Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=中山障害着回数6; column=Jyo12Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo13Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京平地着回数1; column=Jyo13Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo13Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京平地着回数2; column=Jyo13Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo13Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京平地着回数3; column=Jyo13Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo13Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京平地着回数4; column=Jyo13Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo13Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京平地着回数5; column=Jyo13Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo13Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京平地着回数6; column=Jyo13Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo14Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京障害着回数1; column=Jyo14Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo14Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京障害着回数2; column=Jyo14Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo14Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京障害着回数3; column=Jyo14Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo14Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京障害着回数4; column=Jyo14Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo14Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京障害着回数5; column=Jyo14Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo14Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=中京障害着回数6; column=Jyo14Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo15Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都平地着回数1; column=Jyo15Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo15Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都平地着回数2; column=Jyo15Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo15Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都平地着回数3; column=Jyo15Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo15Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都平地着回数4; column=Jyo15Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo15Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都平地着回数5; column=Jyo15Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo15Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都平地着回数6; column=Jyo15Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo16Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都障害着回数1; column=Jyo16Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo16Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都障害着回数2; column=Jyo16Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo16Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都障害着回数3; column=Jyo16Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo16Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都障害着回数4; column=Jyo16Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo16Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都障害着回数5; column=Jyo16Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo16Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=京都障害着回数6; column=Jyo16Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo17Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神平地着回数1; column=Jyo17Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo17Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神平地着回数2; column=Jyo17Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo17Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神平地着回数3; column=Jyo17Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo17Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神平地着回数4; column=Jyo17Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo17Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神平地着回数5; column=Jyo17Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo17Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神平地着回数6; column=Jyo17Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo18Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神障害着回数1; column=Jyo18Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo18Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神障害着回数2; column=Jyo18Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo18Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神障害着回数3; column=Jyo18Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo18Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神障害着回数4; column=Jyo18Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo18Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神障害着回数5; column=Jyo18Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo18Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=阪神障害着回数6; column=Jyo18Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo19Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉平地着回数1; column=Jyo19Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo19Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉平地着回数2; column=Jyo19Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo19Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉平地着回数3; column=Jyo19Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo19Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉平地着回数4; column=Jyo19Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo19Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉平地着回数5; column=Jyo19Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo19Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉平地着回数6; column=Jyo19Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Jyo20Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉障害着回数1; column=Jyo20Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Jyo20Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉障害着回数2; column=Jyo20Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Jyo20Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉障害着回数3; column=Jyo20Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Jyo20Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉障害着回数4; column=Jyo20Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Jyo20Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉障害着回数5; column=Jyo20Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Jyo20Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=小倉障害着回数6; column=Jyo20Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Kyori1Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数1; column=Kyori1Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Kyori1Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数2; column=Kyori1Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Kyori1Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数3; column=Kyori1Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Kyori1Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数4; column=Kyori1Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Kyori1Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数5; column=Kyori1Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Kyori1Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数6; column=Kyori1Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Kyori2Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数1; column=Kyori2Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Kyori2Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数2; column=Kyori2Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Kyori2Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数3; column=Kyori2Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Kyori2Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数4; column=Kyori2Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Kyori2Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数5; column=Kyori2Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Kyori2Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数6; column=Kyori2Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Kyori3Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数1; column=Kyori3Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Kyori3Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数2; column=Kyori3Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Kyori3Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数3; column=Kyori3Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Kyori3Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数4; column=Kyori3Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Kyori3Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数5; column=Kyori3Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Kyori3Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数6; column=Kyori3Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Kyori4Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数1; column=Kyori4Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Kyori4Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数2; column=Kyori4Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Kyori4Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数3; column=Kyori4Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Kyori4Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数4; column=Kyori4Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Kyori4Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数5; column=Kyori4Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Kyori4Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数6; column=Kyori4Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Kyori5Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数1; column=Kyori5Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Kyori5Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数2; column=Kyori5Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Kyori5Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数3; column=Kyori5Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Kyori5Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数4; column=Kyori5Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Kyori5Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数5; column=Kyori5Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Kyori5Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数6; column=Kyori5Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  `Kyori6Chakukaisu1` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数1; column=Kyori6Chakukaisu1; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=1着の回数（中央のみ）',
  `Kyori6Chakukaisu2` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数2; column=Kyori6Chakukaisu2; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=2着の回数（中央のみ）',
  `Kyori6Chakukaisu3` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数3; column=Kyori6Chakukaisu3; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=3着の回数（中央のみ）',
  `Kyori6Chakukaisu4` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数4; column=Kyori6Chakukaisu4; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=4着の回数（中央のみ）',
  `Kyori6Chakukaisu5` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数5; column=Kyori6Chakukaisu5; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=5着の回数（中央のみ）',
  `Kyori6Chakukaisu6` varchar(6) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数6; column=Kyori6Chakukaisu6; table=N_CHOKYO_SEISEKI; class=蓄積系; doc=12-3-31-CHOKYO_SEISEKI; desc=着外の回数（中央のみ）',
  PRIMARY KEY (`ChokyosiCode`,`Num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='[N] name=調教師マスタ_成績; table=N_CHOKYO_SEISEKI; class=蓄積系';
/*!40101 SET character_set_client = @saved_cs_client */;

--
