-- Table structure for table `N_HYOSU`
-- Table structure for table `N_HYOSU`
--

DROP TABLE IF EXISTS `N_HYOSU`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `N_HYOSU` (
  `RecordSpec` varchar(2) DEFAULT NULL COMMENT '[COL] name=レコード種別ID; column=RecordSpec; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=H1でレコード形式を識別',
  `DataKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=データ区分; column=DataKubun; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=2前日売最終/4確定/5確定(月)/9中止/0削除',
  `MakeDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=データ作成年月日; column=MakeDate; table=N_HYOSU; class=蓄積系; unit=yyyymmdd; doc=12-3-06-HYOSU; desc=作成日(西暦8桁)',
  `Year` varchar(4) NOT NULL COMMENT '[COL] name=開催年; column=Year; table=N_HYOSU; class=蓄積系; unit=yyyy; doc=12-3-06-HYOSU; desc=施行年',
  `MonthDay` varchar(4) DEFAULT NULL COMMENT '[COL] name=開催月日; column=MonthDay; table=N_HYOSU; class=蓄積系; unit=mmdd; doc=12-3-06-HYOSU; desc=施行月日',
  `JyoCD` varchar(2) NOT NULL COMMENT '[COL] name=競馬場コード; column=JyoCD; table=N_HYOSU; class=蓄積系; ref=code:2001; doc=12-3-06-HYOSU; desc=施行競馬場コード',
  `Kaiji` varchar(2) NOT NULL COMMENT '[COL] name=開催回; column=Kaiji; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同年同場の開催回',
  `Nichiji` varchar(2) NOT NULL COMMENT '[COL] name=開催日目; column=Nichiji; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=開催回内の日目',
  `RaceNum` varchar(2) NOT NULL COMMENT '[COL] name=レース番号; column=RaceNum; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=該当レース番号',
  `TorokuTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=登録頭数; column=TorokuTosu; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=出馬表発表時の登録頭数',
  `SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=出走頭数; column=SyussoTosu; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=取消･除外反映後の出走頭数',
  `HatubaiFlag1` varchar(1) DEFAULT NULL COMMENT '[COL] name=発売フラグ(単勝); column=HatubaiFlag1; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=0無/1発売前取消/3発売後取消/7発売あり',
  `HatubaiFlag2` varchar(1) DEFAULT NULL COMMENT '[COL] name=発売フラグ(複勝); column=HatubaiFlag2; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=0無/1発売前取消/3発売後取消/7発売あり',
  `HatubaiFlag3` varchar(1) DEFAULT NULL COMMENT '[COL] name=発売フラグ(枠連); column=HatubaiFlag3; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=0無/1発売前取消/3発売後取消/7発売あり',
  `HatubaiFlag4` varchar(1) DEFAULT NULL COMMENT '[COL] name=発売フラグ(馬連); column=HatubaiFlag4; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=0無/1発売前取消/3発売後取消/7発売あり',
  `HatubaiFlag5` varchar(1) DEFAULT NULL COMMENT '[COL] name=発売フラグ(ワイド); column=HatubaiFlag5; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=0無/1発売前取消/3発売後取消/7発売あり',
  `HatubaiFlag6` varchar(1) DEFAULT NULL COMMENT '[COL] name=発売フラグ(馬単); column=HatubaiFlag6; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=0無/1発売前取消/3発売後取消/7発売あり',
  `HatubaiFlag7` varchar(1) DEFAULT NULL COMMENT '[COL] name=発売フラグ(3連複); column=HatubaiFlag7; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=0無/1発売前取消/3発売後取消/7発売あり',
  `FukuChakuBaraiKey` varchar(1) DEFAULT NULL COMMENT '[COL] name=複勝着払キー; column=FukuChakuBaraiKey; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=0複勝発売なし/2:2着まで/3:3着まで',
  `HenkanUma1` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報1; column=HenkanUma1; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma2` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報2; column=HenkanUma2; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma3` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報3; column=HenkanUma3; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma4` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報4; column=HenkanUma4; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma5` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報5; column=HenkanUma5; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma6` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報6; column=HenkanUma6; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma7` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報7; column=HenkanUma7; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma8` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報8; column=HenkanUma8; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma9` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報9; column=HenkanUma9; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma10` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報10; column=HenkanUma10; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma11` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報11; column=HenkanUma11; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma12` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報12; column=HenkanUma12; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma13` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報13; column=HenkanUma13; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma14` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報14; column=HenkanUma14; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma15` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報15; column=HenkanUma15; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma16` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報16; column=HenkanUma16; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma17` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報17; column=HenkanUma17; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma18` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報18; column=HenkanUma18; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma19` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報19; column=HenkanUma19; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma20` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報20; column=HenkanUma20; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma21` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報21; column=HenkanUma21; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma22` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報22; column=HenkanUma22; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma23` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報23; column=HenkanUma23; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma24` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報24; column=HenkanUma24; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma25` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報25; column=HenkanUma25; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma26` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報26; column=HenkanUma26; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma27` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報27; column=HenkanUma27; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanUma28` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報28; column=HenkanUma28; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象馬番ビット列(該当=1)',
  `HenkanWaku1` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報1; column=HenkanWaku1; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象枠番ビット列(該当=1)',
  `HenkanWaku2` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報2; column=HenkanWaku2; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象枠番ビット列(該当=1)',
  `HenkanWaku3` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報3; column=HenkanWaku3; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象枠番ビット列(該当=1)',
  `HenkanWaku4` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報4; column=HenkanWaku4; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象枠番ビット列(該当=1)',
  `HenkanWaku5` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報5; column=HenkanWaku5; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象枠番ビット列(該当=1)',
  `HenkanWaku6` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報6; column=HenkanWaku6; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象枠番ビット列(該当=1)',
  `HenkanWaku7` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報7; column=HenkanWaku7; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象枠番ビット列(該当=1)',
  `HenkanWaku8` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報8; column=HenkanWaku8; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=返還対象枠番ビット列(該当=1)',
  `HenkanDoWaku1` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報1; column=HenkanDoWaku1; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同枠のみ返還ビット列(該当=1)',
  `HenkanDoWaku2` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報2; column=HenkanDoWaku2; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同枠のみ返還ビット列(該当=1)',
  `HenkanDoWaku3` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報3; column=HenkanDoWaku3; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同枠のみ返還ビット列(該当=1)',
  `HenkanDoWaku4` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報4; column=HenkanDoWaku4; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同枠のみ返還ビット列(該当=1)',
  `HenkanDoWaku5` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報5; column=HenkanDoWaku5; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同枠のみ返還ビット列(該当=1)',
  `HenkanDoWaku6` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報6; column=HenkanDoWaku6; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同枠のみ返還ビット列(該当=1)',
  `HenkanDoWaku7` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報7; column=HenkanDoWaku7; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同枠のみ返還ビット列(該当=1)',
  `HenkanDoWaku8` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報8; column=HenkanDoWaku8; table=N_HYOSU; class=蓄積系; doc=12-3-06-HYOSU; desc=同枠のみ返還ビット列(該当=1)',
  `HyoTotal1` varchar(11) DEFAULT NULL COMMENT '[COL] name=単勝票数合計; column=HyoTotal1; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=返還分も含む合計票数',
  `HyoTotal2` varchar(11) DEFAULT NULL COMMENT '[COL] name=複勝票数合計; column=HyoTotal2; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=返還分も含む合計票数',
  `HyoTotal3` varchar(11) DEFAULT NULL COMMENT '[COL] name=枠連票数合計; column=HyoTotal3; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=返還分も含む合計票数',
  `HyoTotal4` varchar(11) DEFAULT NULL COMMENT '[COL] name=馬連票数合計; column=HyoTotal4; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=返還分も含む合計票数',
  `HyoTotal5` varchar(11) DEFAULT NULL COMMENT '[COL] name=ワイド票数合計; column=HyoTotal5; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=返還分も含む合計票数',
  `HyoTotal6` varchar(11) DEFAULT NULL COMMENT '[COL] name=馬単票数合計; column=HyoTotal6; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=返還分も含む合計票数',
  `HyoTotal7` varchar(11) DEFAULT NULL COMMENT '[COL] name=3連複票数合計; column=HyoTotal7; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=返還分も含む合計票数',
  `HyoTotal8` varchar(11) DEFAULT NULL COMMENT '[COL] name=単勝返還票数合計; column=HyoTotal8; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=合計票数から差引いて有効票数を算出',
  `HyoTotal9` varchar(11) DEFAULT NULL COMMENT '[COL] name=複勝返還票数合計; column=HyoTotal9; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=合計票数から差引いて有効票数を算出',
  `HyoTotal10` varchar(11) DEFAULT NULL COMMENT '[COL] name=枠連返還票数合計; column=HyoTotal10; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=合計票数から差引いて有効票数を算出',
  `HyoTotal11` varchar(11) DEFAULT NULL COMMENT '[COL] name=馬連返還票数合計; column=HyoTotal11; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=合計票数から差引いて有効票数を算出',
  `HyoTotal12` varchar(11) DEFAULT NULL COMMENT '[COL] name=ワイド返還票数合計; column=HyoTotal12; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=合計票数から差引いて有効票数を算出',
  `HyoTotal13` varchar(11) DEFAULT NULL COMMENT '[COL] name=馬単返還票数合計; column=HyoTotal13; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=合計票数から差引いて有効票数を算出',
  `HyoTotal14` varchar(11) DEFAULT NULL COMMENT '[COL] name=3連複返還票数合計; column=HyoTotal14; table=N_HYOSU; class=蓄積系; unit=百円; doc=12-3-06-HYOSU; desc=合計票数から差引いて有効票数を算出',
  PRIMARY KEY (`Year`,`JyoCD`,`Kaiji`,`Nichiji`,`RaceNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='[N] name=票数; table=N_HYOSU; class=蓄積系';
/*!40101 SET character_set_client = @saved_cs_client */;

--
