-- Table structure for table `N_KISYU`
-- Table structure for table `N_KISYU`
--

DROP TABLE IF EXISTS `N_KISYU`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `N_KISYU` (
  `RecordSpec` varchar(2) DEFAULT NULL COMMENT '[COL] name=レコード種別ID; column=RecordSpec; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=KSでレコード形式を識別',
  `DataKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=データ区分; column=DataKubun; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=1新規登録/2更新/0削除',
  `MakeDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=データ作成年月日; column=MakeDate; table=N_KISYU; class=蓄積系; unit=yyyymmdd; doc=12-3-28-KISYU; desc=西暦4桁+月日各2桁',
  `KisyuCode` varchar(5) NOT NULL COMMENT '[COL] name=騎手コード; column=KisyuCode; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; key=○',
  `DelKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=騎手抹消区分; column=DelKubun; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=0現役/1抹消',
  `IssueDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=騎手免許交付年月日; column=IssueDate; table=N_KISYU; class=蓄積系; unit=yyyymmdd; doc=12-3-28-KISYU',
  `DelDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=騎手免許抹消年月日; column=DelDate; table=N_KISYU; class=蓄積系; unit=yyyymmdd; doc=12-3-28-KISYU',
  `BirthDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=生年月日; column=BirthDate; table=N_KISYU; class=蓄積系; unit=yyyymmdd; doc=12-3-28-KISYU',
  `KisyuName` varchar(34) DEFAULT NULL COMMENT '[COL] name=騎手名; column=KisyuName; table=N_KISYU; class=蓄積系; unit=全角17; doc=12-3-28-KISYU; desc=姓+全角空白1+名（外国人は連続17文字）',
  `reserved` varchar(34) DEFAULT NULL COMMENT '[COL] name=予備; column=reserved; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU',
  `KisyuNameKana` varchar(30) DEFAULT NULL COMMENT '[COL] name=騎手名半角ｶﾅ; column=KisyuNameKana; table=N_KISYU; class=蓄積系; unit=半角30; doc=12-3-28-KISYU; desc=姓15+名15（外国人は連続30）',
  `KisyuRyakusyo` varchar(8) DEFAULT NULL COMMENT '[COL] name=騎手名略称; column=KisyuRyakusyo; table=N_KISYU; class=蓄積系; unit=全角4; doc=12-3-28-KISYU',
  `KisyuNameEng` varchar(80) DEFAULT NULL COMMENT '[COL] name=騎手名欧字; column=KisyuNameEng; table=N_KISYU; class=蓄積系; unit=半角80; doc=12-3-28-KISYU; desc=姓+半角空白1+名（フルネーム）',
  `SexCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=性別区分; column=SexCD; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=1男性/2女性',
  `SikakuCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=騎乗資格コード; column=SikakuCD; table=N_KISYU; class=蓄積系; ref=code:2302; doc=12-3-28-KISYU',
  `MinaraiCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=騎手見習コード; column=MinaraiCD; table=N_KISYU; class=蓄積系; ref=code:2303; doc=12-3-28-KISYU',
  `TozaiCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=騎手東西所属コード; column=TozaiCD; table=N_KISYU; class=蓄積系; ref=code:2301; doc=12-3-28-KISYU',
  `Syotai` varchar(20) DEFAULT NULL COMMENT '[COL] name=招待地域名; column=Syotai; table=N_KISYU; class=蓄積系; unit=全角10; doc=12-3-28-KISYU',
  `ChokyosiCode` varchar(5) DEFAULT NULL COMMENT '[COL] name=所属調教師コード; column=ChokyosiCode; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=所属厩舎の調教師コード（フリーはALL0）',
  `ChokyosiRyakusyo` varchar(8) DEFAULT NULL COMMENT '[COL] name=所属調教師名略称; column=ChokyosiRyakusyo; table=N_KISYU; class=蓄積系; unit=全角4; doc=12-3-28-KISYU',
  `HatuKiJyo1Hatukijyoid` varchar(16) DEFAULT NULL COMMENT '[COL] name=初騎乗1_年月日場回日R; column=HatuKiJyo1Hatukijyoid; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=平地初騎乗/レース詳細のキー情報',
  `HatuKiJyo1SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=初騎乗1_出走頭数; column=HatuKiJyo1SyussoTosu; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=登録頭数から取消・除外等を除いた頭数',
  `HatuKiJyo1KettoNum` varchar(10) DEFAULT NULL COMMENT '[COL] name=初騎乗1_血統登録番号; column=HatuKiJyo1KettoNum; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; unit=yyyy+品種1+5桁; ref=code:2201',
  `HatuKiJyo1Bamei` varchar(36) DEFAULT NULL COMMENT '[COL] name=初騎乗1_馬名; column=HatuKiJyo1Bamei; table=N_KISYU; class=蓄積系; unit=全角18; doc=12-3-28-KISYU',
  `HatuKiJyo1KakuteiJyuni` varchar(2) DEFAULT NULL COMMENT '[COL] name=初騎乗1_確定着順; column=HatuKiJyo1KakuteiJyuni; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU',
  `HatuKiJyo1IJyoCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=初騎乗1_異常区分コード; column=HatuKiJyo1IJyoCD; table=N_KISYU; class=蓄積系; ref=code:2101; doc=12-3-28-KISYU',
  `HatuKiJyo2Hatukijyoid` varchar(16) DEFAULT NULL COMMENT '[COL] name=初騎乗2_年月日場回日R; column=HatuKiJyo2Hatukijyoid; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=障害初騎乗/レース詳細のキー情報',
  `HatuKiJyo2SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=初騎乗2_出走頭数; column=HatuKiJyo2SyussoTosu; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=登録頭数から取消・除外等を除いた頭数',
  `HatuKiJyo2KettoNum` varchar(10) DEFAULT NULL COMMENT '[COL] name=初騎乗2_血統登録番号; column=HatuKiJyo2KettoNum; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; unit=yyyy+品種1+5桁; ref=code:2201',
  `HatuKiJyo2Bamei` varchar(36) DEFAULT NULL COMMENT '[COL] name=初騎乗2_馬名; column=HatuKiJyo2Bamei; table=N_KISYU; class=蓄積系; unit=全角18; doc=12-3-28-KISYU',
  `HatuKiJyo2KakuteiJyuni` varchar(2) DEFAULT NULL COMMENT '[COL] name=初騎乗2_確定着順; column=HatuKiJyo2KakuteiJyuni; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU',
  `HatuKiJyo2IJyoCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=初騎乗2_異常区分コード; column=HatuKiJyo2IJyoCD; table=N_KISYU; class=蓄積系; ref=code:2101; doc=12-3-28-KISYU',
  `HatuSyori1Hatusyoriid` varchar(16) DEFAULT NULL COMMENT '[COL] name=初勝利1_年月日場回日R; column=HatuSyori1Hatusyoriid; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=平地初勝利/レース詳細のキー情報',
  `HatuSyori1SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=初勝利1_出走頭数; column=HatuSyori1SyussoTosu; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=登録頭数から取消・除外等を除いた頭数',
  `HatuSyori1KettoNum` varchar(10) DEFAULT NULL COMMENT '[COL] name=初勝利1_血統登録番号; column=HatuSyori1KettoNum; table=N_KISYU; class=蓄積系; unit=yyyy+品種1+5桁; ref=code:2201; doc=12-3-28-KISYU',
  `HatuSyori1Bamei` varchar(36) DEFAULT NULL COMMENT '[COL] name=初勝利1_馬名; column=HatuSyori1Bamei; table=N_KISYU; class=蓄積系; unit=全角18; doc=12-3-28-KISYU',
  `HatuSyori2Hatusyoriid` varchar(16) DEFAULT NULL COMMENT '[COL] name=初勝利2_年月日場回日R; column=HatuSyori2Hatusyoriid; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=障害初勝利/レース詳細のキー情報',
  `HatuSyori2SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=初勝利2_出走頭数; column=HatuSyori2SyussoTosu; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=登録頭数から取消・除外等を除いた頭数',
  `HatuSyori2KettoNum` varchar(10) DEFAULT NULL COMMENT '[COL] name=初勝利2_血統登録番号; column=HatuSyori2KettoNum; table=N_KISYU; class=蓄積系; unit=yyyy+品種1+5桁; ref=code:2201; doc=12-3-28-KISYU',
  `HatuSyori2Bamei` varchar(36) DEFAULT NULL COMMENT '[COL] name=初勝利2_馬名; column=HatuSyori2Bamei; table=N_KISYU; class=蓄積系; unit=全角18; doc=12-3-28-KISYU',
  `SaikinJyusyo1SaikinJyusyoid` varchar(16) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_年月日場回日R; column=SaikinJyusyo1SaikinJyusyoid; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=レース詳細のキー情報',
  `SaikinJyusyo1Hondai` varchar(60) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_競走名本題; column=SaikinJyusyo1Hondai; table=N_KISYU; class=蓄積系; unit=全角30; doc=12-3-28-KISYU',
  `SaikinJyusyo1Ryakusyo10` varchar(20) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_競走名略称10字; column=SaikinJyusyo1Ryakusyo10; table=N_KISYU; class=蓄積系; unit=全角10; doc=12-3-28-KISYU',
  `SaikinJyusyo1Ryakusyo6` varchar(12) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_競走名略称6字; column=SaikinJyusyo1Ryakusyo6; table=N_KISYU; class=蓄積系; unit=全角6; doc=12-3-28-KISYU',
  `SaikinJyusyo1Ryakusyo3` varchar(6) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_競走名略称3字; column=SaikinJyusyo1Ryakusyo3; table=N_KISYU; class=蓄積系; unit=全角3; doc=12-3-28-KISYU',
  `SaikinJyusyo1GradeCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_グレードコード; column=SaikinJyusyo1GradeCD; table=N_KISYU; class=蓄積系; ref=code:2003; doc=12-3-28-KISYU',
  `SaikinJyusyo1SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_出走頭数; column=SaikinJyusyo1SyussoTosu; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=取消・除外等を除いた頭数',
  `SaikinJyusyo1KettoNum` varchar(10) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_血統登録番号; column=SaikinJyusyo1KettoNum; table=N_KISYU; class=蓄積系; unit=yyyy+品種1+5桁; ref=code:2201; doc=12-3-28-KISYU',
  `SaikinJyusyo1Bamei` varchar(36) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利1_馬名; column=SaikinJyusyo1Bamei; table=N_KISYU; class=蓄積系; unit=全角18; doc=12-3-28-KISYU',
  `SaikinJyusyo2SaikinJyusyoid` varchar(16) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_年月日場回日R; column=SaikinJyusyo2SaikinJyusyoid; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=レース詳細のキー情報',
  `SaikinJyusyo2Hondai` varchar(60) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_競走名本題; column=SaikinJyusyo2Hondai; table=N_KISYU; class=蓄積系; unit=全角30; doc=12-3-28-KISYU',
  `SaikinJyusyo2Ryakusyo10` varchar(20) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_競走名略称10字; column=SaikinJyusyo2Ryakusyo10; table=N_KISYU; class=蓄積系; unit=全角10; doc=12-3-28-KISYU',
  `SaikinJyusyo2Ryakusyo6` varchar(12) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_競走名略称6字; column=SaikinJyusyo2Ryakusyo6; table=N_KISYU; class=蓄積系; unit=全角6; doc=12-3-28-KISYU',
  `SaikinJyusyo2Ryakusyo3` varchar(6) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_競走名略称3字; column=SaikinJyusyo2Ryakusyo3; table=N_KISYU; class=蓄積系; unit=全角3; doc=12-3-28-KISYU',
  `SaikinJyusyo2GradeCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_グレードコード; column=SaikinJyusyo2GradeCD; table=N_KISYU; class=蓄積系; ref=code:2003; doc=12-3-28-KISYU',
  `SaikinJyusyo2SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_出走頭数; column=SaikinJyusyo2SyussoTosu; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=取消・除外等を除いた頭数',
  `SaikinJyusyo2KettoNum` varchar(10) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_血統登録番号; column=SaikinJyusyo2KettoNum; table=N_KISYU; class=蓄積系; unit=yyyy+品種1+5桁; ref=code:2201; doc=12-3-28-KISYU',
  `SaikinJyusyo2Bamei` varchar(36) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利2_馬名; column=SaikinJyusyo2Bamei; table=N_KISYU; class=蓄積系; unit=全角18; doc=12-3-28-KISYU',
  `SaikinJyusyo3SaikinJyusyoid` varchar(16) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_年月日場回日R; column=SaikinJyusyo3SaikinJyusyoid; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=レース詳細のキー情報',
  `SaikinJyusyo3Hondai` varchar(60) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_競走名本題; column=SaikinJyusyo3Hondai; table=N_KISYU; class=蓄積系; unit=全角30; doc=12-3-28-KISYU',
  `SaikinJyusyo3Ryakusyo10` varchar(20) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_競走名略称10字; column=SaikinJyusyo3Ryakusyo10; table=N_KISYU; class=蓄積系; unit=全角10; doc=12-3-28-KISYU',
  `SaikinJyusyo3Ryakusyo6` varchar(12) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_競走名略称6字; column=SaikinJyusyo3Ryakusyo6; table=N_KISYU; class=蓄積系; unit=全角6; doc=12-3-28-KISYU',
  `SaikinJyusyo3Ryakusyo3` varchar(6) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_競走名略称3字; column=SaikinJyusyo3Ryakusyo3; table=N_KISYU; class=蓄積系; unit=全角3; doc=12-3-28-KISYU',
  `SaikinJyusyo3GradeCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_グレードコード; column=SaikinJyusyo3GradeCD; table=N_KISYU; class=蓄積系; ref=code:2003; doc=12-3-28-KISYU',
  `SaikinJyusyo3SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_出走頭数; column=SaikinJyusyo3SyussoTosu; table=N_KISYU; class=蓄積系; doc=12-3-28-KISYU; desc=取消・除外等を除いた頭数',
  `SaikinJyusyo3KettoNum` varchar(10) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_血統登録番号; column=SaikinJyusyo3KettoNum; table=N_KISYU; class=蓄積系; unit=yyyy+品種1+5桁; ref=code:2201; doc=12-3-28-KISYU',
  `SaikinJyusyo3Bamei` varchar(36) DEFAULT NULL COMMENT '[COL] name=最近重賞勝利3_馬名; column=SaikinJyusyo3Bamei; table=N_KISYU; class=蓄積系; unit=全角18; doc=12-3-28-KISYU',
  PRIMARY KEY (`KisyuCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='[N] name=騎手マスタ; table=N_KISYU; class=蓄積系';
/*!40101 SET character_set_client = @saved_cs_client */;

--
