-- Table structure for table `N_RACE`
-- Table structure for table `N_RACE`
--

DROP TABLE IF EXISTS `N_RACE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `N_RACE` (
  `RecordSpec` varchar(2) DEFAULT NULL COMMENT '[COL] name=レコード種別ID; column=RecordSpec; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=RA/レコード形式を識別',
  `DataKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=データ区分; column=DataKubun; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=出走馬名表/出馬表/速報成績等を区分',
  `MakeDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=データ作成年月日; column=MakeDate; table=N_RACE; class=蓄積系; unit=yyyymmdd; doc=12-3-03-RACE; desc=作成日(西暦8桁)',
  `Year` varchar(4) NOT NULL COMMENT '[COL] name=開催年; column=Year; table=N_RACE; class=蓄積系; unit=yyyy; doc=12-3-03-RACE; desc=施行年',
  `MonthDay` varchar(4) NOT NULL COMMENT '[COL] name=開催月日; column=MonthDay; table=N_RACE; class=蓄積系; unit=mmdd; doc=12-3-03-RACE; desc=施行月日',
  `JyoCD` varchar(2) NOT NULL COMMENT '[COL] name=競馬場コード; column=JyoCD; table=N_RACE; class=蓄積系; ref=code:2001; doc=12-3-03-RACE; desc=施行競馬場コード',
  `Kaiji` varchar(2) NOT NULL COMMENT '[COL] name=開催回; column=Kaiji; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=同年同場での開催回',
  `Nichiji` varchar(2) NOT NULL COMMENT '[COL] name=開催日目; column=Nichiji; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=開催回内の日目',
  `RaceNum` varchar(2) NOT NULL COMMENT '[COL] name=レース番号; column=RaceNum; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=該当レース番号(海外等で無い場合あり)',
  `YoubiCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=曜日コード; column=YoubiCD; table=N_RACE; class=蓄積系; ref=code:2002; doc=12-3-03-RACE; desc=施行曜日',
  `TokuNum` varchar(4) DEFAULT NULL COMMENT '[COL] name=特別競走番号; column=TokuNum; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=重賞のみ設定(例外あり)',
  `Hondai` varchar(60) DEFAULT NULL COMMENT '[COL] name=競走名本題; column=Hondai; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=レース名の本題',
  `Fukudai` varchar(60) DEFAULT NULL COMMENT '[COL] name=競走名副題; column=Fukudai; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=スポンサー名等',
  `Kakko` varchar(60) DEFAULT NULL COMMENT '[COL] name=競走名カッコ内; column=Kakko; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=条件/通称/トライアル対象等',
  `HondaiEng` varchar(120) DEFAULT NULL COMMENT '[COL] name=競走名本題欧字; column=HondaiEng; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=英字本題',
  `FukudaiEng` varchar(120) DEFAULT NULL COMMENT '[COL] name=競走名副題欧字; column=FukudaiEng; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=英字副題',
  `KakkoEng` varchar(120) DEFAULT NULL COMMENT '[COL] name=競走名カッコ内欧字; column=KakkoEng; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=英字カッコ内',
  `Ryakusyo10` varchar(20) DEFAULT NULL COMMENT '[COL] name=競走名略称10字; column=Ryakusyo10; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=全角10字略称',
  `Ryakusyo6` varchar(12) DEFAULT NULL COMMENT '[COL] name=競走名略称6字; column=Ryakusyo6; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=全角6字略称',
  `Ryakusyo3` varchar(6) DEFAULT NULL COMMENT '[COL] name=競走名略称3字; column=Ryakusyo3; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=全角3字略称',
  `Kubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=競走名区分; column=Kubun; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=重賞回次の付与位置(本題/副題/括弧内)',
  `Nkai` varchar(3) DEFAULT NULL COMMENT '[COL] name=重賞回次; column=Nkai; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=重賞としての通算回数',
  `GradeCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=グレードコード; column=GradeCD; table=N_RACE; class=蓄積系; ref=code:2003; doc=12-3-03-RACE; desc=GI/GII/GIII等',
  `GradeCDBefore` varchar(1) DEFAULT NULL COMMENT '[COL] name=変更前グレードコード; column=GradeCDBefore; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=変更前のグレード',
  `SyubetuCD` varchar(2) DEFAULT NULL COMMENT '[COL] name=競走種別コード; column=SyubetuCD; table=N_RACE; class=蓄積系; ref=code:2005; doc=12-3-03-RACE; desc=競走種別',
  `KigoCD` varchar(3) DEFAULT NULL COMMENT '[COL] name=競走記号コード; column=KigoCD; table=N_RACE; class=蓄積系; ref=code:2006; doc=12-3-03-RACE; desc=記号(国際/牝等)',
  `JyuryoCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=重量種別コード; column=JyuryoCD; table=N_RACE; class=蓄積系; ref=code:2008; doc=12-3-03-RACE; desc=定量/ハンデ等',
  `JyokenCD1` varchar(3) DEFAULT NULL COMMENT '[COL] name=競走条件コード(2歳); column=JyokenCD1; table=N_RACE; class=蓄積系; ref=code:2007; doc=12-3-03-RACE; desc=2歳条件',
  `JyokenCD2` varchar(3) DEFAULT NULL COMMENT '[COL] name=競走条件コード(3歳); column=JyokenCD2; table=N_RACE; class=蓄積系; ref=code:2007; doc=12-3-03-RACE; desc=3歳条件',
  `JyokenCD3` varchar(3) DEFAULT NULL COMMENT '[COL] name=競走条件コード(4歳); column=JyokenCD3; table=N_RACE; class=蓄積系; ref=code:2007; doc=12-3-03-RACE; desc=4歳条件',
  `JyokenCD4` varchar(3) DEFAULT NULL COMMENT '[COL] name=競走条件コード(5歳以上); column=JyokenCD4; table=N_RACE; class=蓄積系; ref=code:2007; doc=12-3-03-RACE; desc=5歳以上条件',
  `JyokenCD5` varchar(3) DEFAULT NULL COMMENT '[COL] name=競走条件コード(最若年); column=JyokenCD5; table=N_RACE; class=蓄積系; ref=code:2007; doc=12-3-03-RACE; desc=最若年条件',
  `JyokenName` varchar(60) DEFAULT NULL COMMENT '[COL] name=競走条件名称; column=JyokenName; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=地方競馬のみ設定',
  `Kyori` varchar(4) DEFAULT NULL COMMENT '[COL] name=距離; column=Kyori; table=N_RACE; class=蓄積系; unit=m; doc=12-3-03-RACE; desc=メートル',
  `KyoriBefore` varchar(4) DEFAULT NULL COMMENT '[COL] name=変更前距離; column=KyoriBefore; table=N_RACE; class=蓄積系; unit=m; doc=12-3-03-RACE; desc=変更前の距離',
  `TrackCD` varchar(2) DEFAULT NULL COMMENT '[COL] name=トラックコード; column=TrackCD; table=N_RACE; class=蓄積系; ref=code:2009; doc=12-3-03-RACE; desc=芝/ダ/障等',
  `TrackCDBefore` varchar(2) DEFAULT NULL COMMENT '[COL] name=変更前トラックコード; column=TrackCDBefore; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=変更前の走路コード',
  `CourseKubunCD` varchar(2) DEFAULT NULL COMMENT '[COL] name=コース区分; column=CourseKubunCD; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=A～E等の使用コース',
  `CourseKubunCDBefore` varchar(2) DEFAULT NULL COMMENT '[COL] name=変更前コース区分; column=CourseKubunCDBefore; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=変更前のコース区分',
  `Honsyokin1` varchar(8) DEFAULT NULL COMMENT '[COL] name=本賞金1; column=Honsyokin1; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～5着の本賞金(同着考慮)',
  `Honsyokin2` varchar(8) DEFAULT NULL COMMENT '[COL] name=本賞金2; column=Honsyokin2; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～5着の本賞金(同着考慮)',
  `Honsyokin3` varchar(8) DEFAULT NULL COMMENT '[COL] name=本賞金3; column=Honsyokin3; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～5着の本賞金(同着考慮)',
  `Honsyokin4` varchar(8) DEFAULT NULL COMMENT '[COL] name=本賞金4; column=Honsyokin4; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～5着の本賞金(同着考慮)',
  `Honsyokin5` varchar(8) DEFAULT NULL COMMENT '[COL] name=本賞金5; column=Honsyokin5; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～5着の本賞金(同着考慮)',
  `Honsyokin6` varchar(8) DEFAULT NULL COMMENT '[COL] name=本賞金6; column=Honsyokin6; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～5着の本賞金(同着考慮)',
  `Honsyokin7` varchar(8) DEFAULT NULL COMMENT '[COL] name=本賞金7; column=Honsyokin7; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～5着の本賞金(同着考慮)',
  `HonsyokinBefore1` varchar(8) DEFAULT NULL COMMENT '[COL] name=変更前本賞金1; column=HonsyokinBefore1; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=同着等で分配変更前',
  `HonsyokinBefore2` varchar(8) DEFAULT NULL COMMENT '[COL] name=変更前本賞金2; column=HonsyokinBefore2; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=同着等で分配変更前',
  `HonsyokinBefore3` varchar(8) DEFAULT NULL COMMENT '[COL] name=変更前本賞金3; column=HonsyokinBefore3; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=同着等で分配変更前',
  `HonsyokinBefore4` varchar(8) DEFAULT NULL COMMENT '[COL] name=変更前本賞金4; column=HonsyokinBefore4; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=同着等で分配変更前',
  `HonsyokinBefore5` varchar(8) DEFAULT NULL COMMENT '[COL] name=変更前本賞金5; column=HonsyokinBefore5; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=同着等で分配変更前',
  `Fukasyokin1` varchar(8) DEFAULT NULL COMMENT '[COL] name=付加賞金1; column=Fukasyokin1; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～3着の付加賞金(同着考慮)',
  `Fukasyokin2` varchar(8) DEFAULT NULL COMMENT '[COL] name=付加賞金2; column=Fukasyokin2; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～3着の付加賞金(同着考慮)',
  `Fukasyokin3` varchar(8) DEFAULT NULL COMMENT '[COL] name=付加賞金3; column=Fukasyokin3; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～3着の付加賞金(同着考慮)',
  `Fukasyokin4` varchar(8) DEFAULT NULL COMMENT '[COL] name=付加賞金4; column=Fukasyokin4; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～3着の付加賞金(同着考慮)',
  `Fukasyokin5` varchar(8) DEFAULT NULL COMMENT '[COL] name=付加賞金5; column=Fukasyokin5; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=1～3着の付加賞金(同着考慮)',
  `FukasyokinBefore1` varchar(8) DEFAULT NULL COMMENT '[COL] name=変更前付加賞金1; column=FukasyokinBefore1; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=付加賞金分配の変更前',
  `FukasyokinBefore2` varchar(8) DEFAULT NULL COMMENT '[COL] name=変更前付加賞金2; column=FukasyokinBefore2; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=付加賞金分配の変更前',
  `FukasyokinBefore3` varchar(8) DEFAULT NULL COMMENT '[COL] name=変更前付加賞金3; column=FukasyokinBefore3; table=N_RACE; class=蓄積系; unit=百円; doc=12-3-03-RACE; desc=付加賞金分配の変更前',
  `HassoTime` varchar(4) DEFAULT NULL COMMENT '[COL] name=発走時刻; column=HassoTime; table=N_RACE; class=蓄積系; unit=hhmm; doc=12-3-03-RACE; desc=時分4桁',
  `HassoTimeBefore` varchar(4) DEFAULT NULL COMMENT '[COL] name=変更前発走時刻; column=HassoTimeBefore; table=N_RACE; class=蓄積系; unit=hhmm; doc=12-3-03-RACE; desc=変更前の時刻',
  `TorokuTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=登録頭数; column=TorokuTosu; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=各時点での登録頭数',
  `SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=出走頭数; column=SyussoTosu; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=実際に出走した頭数',
  `NyusenTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=入線頭数; column=NyusenTosu; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=出走頭数から競走中止を除く',
  `TenkoCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=天候コード; column=TenkoCD; table=N_RACE; class=蓄積系; ref=code:2011; doc=12-3-03-RACE; desc=天候コード',
  `SibaBabaCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=芝馬場状態コード; column=SibaBabaCD; table=N_RACE; class=蓄積系; ref=code:2010; doc=12-3-03-RACE; desc=芝の馬場状態',
  `DirtBabaCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=ダート馬場状態コード; column=DirtBabaCD; table=N_RACE; class=蓄積系; ref=code:2010; doc=12-3-03-RACE; desc=ダートの馬場状態',
  `LapTime1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム1; column=LapTime1; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム2; column=LapTime2; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム3; column=LapTime3; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム4; column=LapTime4; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム5; column=LapTime5; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム6; column=LapTime6; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime7` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム7; column=LapTime7; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime8` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム8; column=LapTime8; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime9` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム9; column=LapTime9; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime10` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム10; column=LapTime10; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime11` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム11; column=LapTime11; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime12` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム12; column=LapTime12; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime13` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム13; column=LapTime13; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime14` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム14; column=LapTime14; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime15` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム15; column=LapTime15; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime16` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム16; column=LapTime16; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime17` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム17; column=LapTime17; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime18` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム18; column=LapTime18; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime19` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム19; column=LapTime19; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime20` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム20; column=LapTime20; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime21` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム21; column=LapTime21; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime22` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム22; column=LapTime22; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime23` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム23; column=LapTime23; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime24` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム24; column=LapTime24; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `LapTime25` varchar(3) DEFAULT NULL COMMENT '[COL] name=ラップタイム25; column=LapTime25; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=先頭馬の各ハロンラップ(平地)',
  `SyogaiMileTime` varchar(4) DEFAULT NULL COMMENT '[COL] name=障害マイルタイム; column=SyogaiMileTime; table=N_RACE; class=蓄積系; unit=分秒; doc=12-3-03-RACE; desc=先頭馬の1600m通過(障害)',
  `HaronTimeS3` varchar(3) DEFAULT NULL COMMENT '[COL] name=前3ハロン; column=HaronTimeS3; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=ラップ前半3F合計(平地)',
  `HaronTimeS4` varchar(3) DEFAULT NULL COMMENT '[COL] name=前4ハロン; column=HaronTimeS4; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=ラップ前半4F合計(平地)',
  `HaronTimeL3` varchar(3) DEFAULT NULL COMMENT '[COL] name=後3ハロン; column=HaronTimeL3; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=ラップ後半3F合計',
  `HaronTimeL4` varchar(3) DEFAULT NULL COMMENT '[COL] name=後4ハロン; column=HaronTimeL4; table=N_RACE; class=蓄積系; unit=秒; doc=12-3-03-RACE; desc=ラップ後半4F合計',
  `Corner1` varchar(1) DEFAULT NULL COMMENT '[COL] name=コーナー1; column=Corner1; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=1:1角 2:2角 3:3角 4:4角',
  `Syukaisu1` varchar(1) DEFAULT NULL COMMENT '[COL] name=周回数1; column=Syukaisu1; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=1:1周 2:2周 3:3周',
  `Jyuni1` varchar(70) DEFAULT NULL COMMENT '[COL] name=通過順位1; column=Jyuni1; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=先頭内側からの通過順位(書式あり)',
  `Corner2` varchar(1) DEFAULT NULL COMMENT '[COL] name=コーナー2; column=Corner2; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=1:1角 2:2角 3:3角 4:4角',
  `Syukaisu2` varchar(1) DEFAULT NULL COMMENT '[COL] name=周回数2; column=Syukaisu2; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=1:1周 2:2周 3:3周',
  `Jyuni2` varchar(70) DEFAULT NULL COMMENT '[COL] name=通過順位2; column=Jyuni2; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=先頭内側からの通過順位(書式あり)',
  `Corner3` varchar(1) DEFAULT NULL COMMENT '[COL] name=コーナー3; column=Corner3; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=1:1角 2:2角 3:3角 4:4角',
  `Syukaisu3` varchar(1) DEFAULT NULL COMMENT '[COL] name=周回数3; column=Syukaisu3; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=1:1周 2:2周 3:3周',
  `Jyuni3` varchar(70) DEFAULT NULL COMMENT '[COL] name=通過順位3; column=Jyuni3; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=先頭内側からの通過順位(書式あり)',
  `Corner4` varchar(1) DEFAULT NULL COMMENT '[COL] name=コーナー4; column=Corner4; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=1:1角 2:2角 3:3角 4:4角',
  `Syukaisu4` varchar(1) DEFAULT NULL COMMENT '[COL] name=周回数4; column=Syukaisu4; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=1:1周 2:2周 3:3周',
  `Jyuni4` varchar(70) DEFAULT NULL COMMENT '[COL] name=通過順位4; column=Jyuni4; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=先頭内側からの通過順位(書式あり)',
  `RecordUpKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=レコード更新区分; column=RecordUpKubun; table=N_RACE; class=蓄積系; doc=12-3-03-RACE; desc=0初期/1基準タイム/2コースレコード更新',
  PRIMARY KEY (`Year`,`MonthDay`,`JyoCD`,`Kaiji`,`Nichiji`,`RaceNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='[N] name=レース詳細; table=N_RACE; class=蓄積系';
/*!40101 SET character_set_client = @saved_cs_client */;

--
