-- Table structure for table `N_UMA`
-- Table structure for table `N_UMA`
--

DROP TABLE IF EXISTS `N_UMA`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `N_UMA` (
  `RecordSpec` varchar(2) DEFAULT NULL COMMENT '[COL] name=レコード種別ID; column=RecordSpec; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=UMでレコード形式を識別',
  `DataKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=データ区分; column=DataKubun; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1新規/2馬名変更/3再登録/4その他更新/9抹消/0削除',
  `MakeDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=データ作成年月日; column=MakeDate; table=N_UMA; class=蓄積系; unit=yyyymmdd; doc=12-3-27-UMA; desc=西暦4桁+月日各2桁',
  `KettoNum` varchar(10) NOT NULL COMMENT '[COL] name=血統登録番号; column=KettoNum; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=生年4桁+品種1桁+数字5桁; ref=code:2201(品種コード)',
  `DelKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=競走馬抹消区分; column=DelKubun; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=0現役/1抹消',
  `RegDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=競走馬登録年月日; column=RegDate; table=N_UMA; class=蓄積系; unit=yyyymmdd; doc=12-3-27-UMA',
  `DelDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=競走馬抹消年月日; column=DelDate; table=N_UMA; class=蓄積系; unit=yyyymmdd; doc=12-3-27-UMA',
  `BirthDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=生年月日; column=BirthDate; table=N_UMA; class=蓄積系; unit=yyyymmdd; doc=12-3-27-UMA',
  `Bamei` varchar(36) DEFAULT NULL COMMENT '[COL] name=馬名; column=Bamei; table=N_UMA; class=蓄積系; unit=全角18; doc=12-3-27-UMA',
  `BameiKana` varchar(36) DEFAULT NULL COMMENT '[COL] name=馬名半角ｶﾅ; column=BameiKana; table=N_UMA; class=蓄積系; unit=半角36; doc=12-3-27-UMA',
  `BameiEng` varchar(60) DEFAULT NULL COMMENT '[COL] name=馬名欧字; column=BameiEng; table=N_UMA; class=蓄積系; unit=半角60; doc=12-3-27-UMA',
  `ZaikyuFlag` varchar(1) DEFAULT NULL COMMENT '[COL] name=JRA施設在きゅうフラグ; column=ZaikyuFlag; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=0施設外/1施設内(2006-06-06以降設定)',
  `Reserved` varchar(19) DEFAULT NULL COMMENT '[COL] name=予備; column=Reserved; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=予備',
  `UmaKigoCD` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬記号コード; column=UmaKigoCD; table=N_UMA; class=蓄積系; ref=code:2204; doc=12-3-27-UMA',
  `SexCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=性別コード; column=SexCD; table=N_UMA; class=蓄積系; ref=code:2202; doc=12-3-27-UMA',
  `HinsyuCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=品種コード; column=HinsyuCD; table=N_UMA; class=蓄積系; ref=code:2201; doc=12-3-27-UMA',
  `KeiroCD` varchar(2) DEFAULT NULL COMMENT '[COL] name=毛色コード; column=KeiroCD; table=N_UMA; class=蓄積系; ref=code:2203; doc=12-3-27-UMA',
  `Ketto3InfoHansyokuNum1` varchar(10) DEFAULT NULL COMMENT '[COL] name=3代血統_繁殖登録番号1(父); column=Ketto3InfoHansyokuNum1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=繁殖馬マスタにリンク',
  `Ketto3InfoBamei1` varchar(36) DEFAULT NULL COMMENT '[COL] name=3代血統_馬名1(父); column=Ketto3InfoBamei1; table=N_UMA; class=蓄積系; unit=全18/半36; doc=12-3-27-UMA; desc=外国馬は繁殖馬マスタ欧字頭36B',
  `Ketto3InfoHansyokuNum2` varchar(10) DEFAULT NULL COMMENT '[COL] name=3代血統_繁殖登録番号2(母); column=Ketto3InfoHansyokuNum2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=繁殖馬マスタにリンク',
  `Ketto3InfoBamei2` varchar(36) DEFAULT NULL COMMENT '[COL] name=3代血統_馬名2(母); column=Ketto3InfoBamei2; table=N_UMA; class=蓄積系; unit=全18/半36; doc=12-3-27-UMA; desc=外国馬は繁殖馬マスタ欧字頭36B',
  `Ketto3InfoHansyokuNum3` varchar(10) DEFAULT NULL COMMENT '[COL] name=3代血統_繁殖登録番号3(父父); column=Ketto3InfoHansyokuNum3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=繁殖馬マスタにリンク',
  `Ketto3InfoBamei3` varchar(36) DEFAULT NULL COMMENT '[COL] name=3代血統_馬名3(父父); column=Ketto3InfoBamei3; table=N_UMA; class=蓄積系; unit=全18/半36; doc=12-3-27-UMA; desc=外国馬は繁殖馬マスタ欧字頭36B',
  `Ketto3InfoHansyokuNum4` varchar(10) DEFAULT NULL COMMENT '[COL] name=3代血統_繁殖登録番号4(父母); column=Ketto3InfoHansyokuNum4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=繁殖馬マスタにリンク',
  `Ketto3InfoBamei4` varchar(36) DEFAULT NULL COMMENT '[COL] name=3代血統_馬名4(父母); column=Ketto3InfoBamei4; table=N_UMA; class=蓄積系; unit=全18/半36; doc=12-3-27-UMA; desc=外国馬は繁殖馬マスタ欧字頭36B',
  `Ketto3InfoHansyokuNum5` varchar(10) DEFAULT NULL COMMENT '[COL] name=3代血統_繁殖登録番号5(母父); column=Ketto3InfoHansyokuNum5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=繁殖馬マスタにリンク',
  `Ketto3InfoBamei5` varchar(36) DEFAULT NULL COMMENT '[COL] name=3代血統_馬名5(母父); column=Ketto3InfoBamei5; table=N_UMA; class=蓄積系; unit=全18/半36; doc=12-3-27-UMA; desc=外国馬は繁殖馬マスタ欧字頭36B',
  `Ketto3InfoHansyokuNum6` varchar(10) DEFAULT NULL COMMENT '[COL] name=3代血統_繁殖登録番号6(母母); column=Ketto3InfoHansyokuNum6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=繁殖馬マスタにリンク',
  `Ketto3InfoBamei6` varchar(36) DEFAULT NULL COMMENT '[COL] name=3代血統_馬名6(母母); column=Ketto3InfoBamei6; table=N_UMA; class=蓄積系; unit=全18/半36; doc=12-3-27-UMA; desc=外国馬は繁殖馬マスタ欧字頭36B',
  `Ketto3InfoHansyokuNum7` varchar(10) DEFAULT NULL,
  `Ketto3InfoBamei7` varchar(36) DEFAULT NULL,
  `Ketto3InfoHansyokuNum8` varchar(10) DEFAULT NULL,
  `Ketto3InfoBamei8` varchar(36) DEFAULT NULL,
  `Ketto3InfoHansyokuNum9` varchar(10) DEFAULT NULL,
  `Ketto3InfoBamei9` varchar(36) DEFAULT NULL,
  `Ketto3InfoHansyokuNum10` varchar(10) DEFAULT NULL,
  `Ketto3InfoBamei10` varchar(36) DEFAULT NULL,
  `Ketto3InfoHansyokuNum11` varchar(10) DEFAULT NULL,
  `Ketto3InfoBamei11` varchar(36) DEFAULT NULL,
  `Ketto3InfoHansyokuNum12` varchar(10) DEFAULT NULL,
  `Ketto3InfoBamei12` varchar(36) DEFAULT NULL,
  `Ketto3InfoHansyokuNum13` varchar(10) DEFAULT NULL,
  `Ketto3InfoBamei13` varchar(36) DEFAULT NULL,
  `Ketto3InfoHansyokuNum14` varchar(10) DEFAULT NULL,
  `Ketto3InfoBamei14` varchar(36) DEFAULT NULL,
  `TozaiCD` varchar(1) DEFAULT NULL COMMENT '[COL] name=東西所属コード; column=TozaiCD; table=N_UMA; class=蓄積系; ref=code:2301; doc=12-3-27-UMA',
  `ChokyosiCode` varchar(5) DEFAULT NULL COMMENT '[COL] name=調教師コード; column=ChokyosiCode; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=調教師マスタへリンク',
  `ChokyosiRyakusyo` varchar(8) DEFAULT NULL COMMENT '[COL] name=調教師名略称; column=ChokyosiRyakusyo; table=N_UMA; class=蓄積系; unit=全角4; doc=12-3-27-UMA',
  `Syotai` varchar(20) DEFAULT NULL COMMENT '[COL] name=招待地域名; column=Syotai; table=N_UMA; class=蓄積系; unit=全角10; doc=12-3-27-UMA',
  `BreederCode` varchar(8) DEFAULT NULL COMMENT '[COL] name=生産者コード; column=BreederCode; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=生産者マスタへリンク',
  `BreederName` varchar(72) DEFAULT NULL COMMENT '[COL] name=生産者名; column=BreederName; table=N_UMA; class=蓄積系; unit=全35/半70; doc=12-3-27-UMA; desc=法人格の表記は除去・外国は欧字頭70B',
  `SanchiName` varchar(20) DEFAULT NULL COMMENT '[COL] name=産地名; column=SanchiName; table=N_UMA; class=蓄積系; unit=全10/半20; doc=12-3-27-UMA; desc=英数は半角設定',
  `BanusiCode` varchar(6) DEFAULT NULL COMMENT '[COL] name=馬主コード; column=BanusiCode; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=馬主マスタへリンク',
  `BanusiName` varchar(64) DEFAULT NULL COMMENT '[COL] name=馬主名; column=BanusiName; table=N_UMA; class=蓄積系; unit=全32/半64; doc=12-3-27-UMA; desc=法人格の表記は除去・外国は欧字頭64B',
  `RuikeiHonsyoHeiti` varchar(9) DEFAULT NULL COMMENT '[COL] name=平地本賞金累計; column=RuikeiHonsyoHeiti; table=N_UMA; class=蓄積系; unit=百円; doc=12-3-27-UMA; desc=中央の平地本賞金合計',
  `RuikeiHonsyoSyogai` varchar(9) DEFAULT NULL COMMENT '[COL] name=障害本賞金累計; column=RuikeiHonsyoSyogai; table=N_UMA; class=蓄積系; unit=百円; doc=12-3-27-UMA; desc=中央の障害本賞金合計',
  `RuikeiFukaHeichi` varchar(9) DEFAULT NULL COMMENT '[COL] name=平地付加賞金累計; column=RuikeiFukaHeichi; table=N_UMA; class=蓄積系; unit=百円; doc=12-3-27-UMA; desc=中央の平地付加賞金合計',
  `RuikeiFukaSyogai` varchar(9) DEFAULT NULL COMMENT '[COL] name=障害付加賞金累計; column=RuikeiFukaSyogai; table=N_UMA; class=蓄積系; unit=百円; doc=12-3-27-UMA; desc=中央の障害付加賞金合計',
  `RuikeiSyutokuHeichi` varchar(9) DEFAULT NULL COMMENT '[COL] name=平地収得賞金累計; column=RuikeiSyutokuHeichi; table=N_UMA; class=蓄積系; unit=百円; doc=12-3-27-UMA; desc=中央+中央以外の平地累積収得賞金',
  `RuikeiSyutokuSyogai` varchar(9) DEFAULT NULL COMMENT '[COL] name=障害収得賞金累計; column=RuikeiSyutokuSyogai; table=N_UMA; class=蓄積系; unit=百円; doc=12-3-27-UMA; desc=中央+中央以外の障害累積収得賞金',
  `SogoChakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=総合着回数1; column=SogoChakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央＋地方＋海外）',
  `SogoChakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=総合着回数2; column=SogoChakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央＋地方＋海外）',
  `SogoChakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=総合着回数3; column=SogoChakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央＋地方＋海外）',
  `SogoChakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=総合着回数4; column=SogoChakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央＋地方＋海外）',
  `SogoChakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=総合着回数5; column=SogoChakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央＋地方＋海外）',
  `SogoChakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=総合着回数6; column=SogoChakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央＋地方＋海外）',
  `ChuoChakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=中央合計着回数1; column=ChuoChakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `ChuoChakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=中央合計着回数2; column=ChuoChakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `ChuoChakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=中央合計着回数3; column=ChuoChakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `ChuoChakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=中央合計着回数4; column=ChuoChakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `ChuoChakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=中央合計着回数5; column=ChuoChakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `ChuoChakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=中央合計着回数6; column=ChuoChakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Ba1Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝直・着回数1; column=Ba1Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Ba1Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝直・着回数2; column=Ba1Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Ba1Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝直・着回数3; column=Ba1Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Ba1Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝直・着回数4; column=Ba1Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Ba1Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝直・着回数5; column=Ba1Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Ba1Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝直・着回数6; column=Ba1Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Ba2Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝右・着回数1; column=Ba2Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Ba2Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝右・着回数2; column=Ba2Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Ba2Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝右・着回数3; column=Ba2Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Ba2Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝右・着回数4; column=Ba2Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Ba2Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝右・着回数5; column=Ba2Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Ba2Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝右・着回数6; column=Ba2Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Ba3Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝左・着回数1; column=Ba3Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Ba3Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝左・着回数2; column=Ba3Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Ba3Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝左・着回数3; column=Ba3Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Ba3Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝左・着回数4; column=Ba3Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Ba3Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝左・着回数5; column=Ba3Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Ba3Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝左・着回数6; column=Ba3Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Ba4Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ直・着回数1; column=Ba4Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Ba4Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ直・着回数2; column=Ba4Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Ba4Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ直・着回数3; column=Ba4Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Ba4Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ直・着回数4; column=Ba4Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Ba4Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ直・着回数5; column=Ba4Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Ba4Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ直・着回数6; column=Ba4Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Ba5Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ右・着回数1; column=Ba5Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Ba5Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ右・着回数2; column=Ba5Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Ba5Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ右・着回数3; column=Ba5Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Ba5Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ右・着回数4; column=Ba5Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Ba5Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ右・着回数5; column=Ba5Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Ba5Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ右・着回数6; column=Ba5Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Ba6Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ左・着回数1; column=Ba6Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Ba6Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ左・着回数2; column=Ba6Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Ba6Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ左・着回数3; column=Ba6Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Ba6Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ左・着回数4; column=Ba6Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Ba6Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ左・着回数5; column=Ba6Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Ba6Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ左・着回数6; column=Ba6Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Ba7Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=障害・着回数1; column=Ba7Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Ba7Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=障害・着回数2; column=Ba7Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Ba7Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=障害・着回数3; column=Ba7Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Ba7Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=障害・着回数4; column=Ba7Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Ba7Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=障害・着回数5; column=Ba7Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Ba7Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=障害・着回数6; column=Ba7Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai1Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝良・着回数1; column=Jyotai1Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai1Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝良・着回数2; column=Jyotai1Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai1Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝良・着回数3; column=Jyotai1Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai1Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝良・着回数4; column=Jyotai1Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai1Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝良・着回数5; column=Jyotai1Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai1Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝良・着回数6; column=Jyotai1Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai2Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝稍・着回数1; column=Jyotai2Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai2Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝稍・着回数2; column=Jyotai2Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai2Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝稍・着回数3; column=Jyotai2Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai2Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝稍・着回数4; column=Jyotai2Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai2Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝稍・着回数5; column=Jyotai2Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai2Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝稍・着回数6; column=Jyotai2Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai3Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝重・着回数1; column=Jyotai3Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai3Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝重・着回数2; column=Jyotai3Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai3Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝重・着回数3; column=Jyotai3Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai3Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝重・着回数4; column=Jyotai3Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai3Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝重・着回数5; column=Jyotai3Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai3Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝重・着回数6; column=Jyotai3Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai4Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝不・着回数1; column=Jyotai4Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai4Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝不・着回数2; column=Jyotai4Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai4Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝不・着回数3; column=Jyotai4Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai4Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝不・着回数4; column=Jyotai4Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai4Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝不・着回数5; column=Jyotai4Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai4Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝不・着回数6; column=Jyotai4Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai5Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ良・着回数1; column=Jyotai5Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai5Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ良・着回数2; column=Jyotai5Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai5Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ良・着回数3; column=Jyotai5Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai5Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ良・着回数4; column=Jyotai5Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai5Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ良・着回数5; column=Jyotai5Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai5Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ良・着回数6; column=Jyotai5Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai6Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ稍・着回数1; column=Jyotai6Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai6Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ稍・着回数2; column=Jyotai6Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai6Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ稍・着回数3; column=Jyotai6Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai6Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ稍・着回数4; column=Jyotai6Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai6Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ稍・着回数5; column=Jyotai6Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai6Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ稍・着回数6; column=Jyotai6Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai7Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ重・着回数1; column=Jyotai7Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai7Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ重・着回数2; column=Jyotai7Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai7Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ重・着回数3; column=Jyotai7Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai7Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ重・着回数4; column=Jyotai7Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai7Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ重・着回数5; column=Jyotai7Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai7Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ重・着回数6; column=Jyotai7Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai8Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ不・着回数1; column=Jyotai8Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai8Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ不・着回数2; column=Jyotai8Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai8Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ不・着回数3; column=Jyotai8Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai8Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ不・着回数4; column=Jyotai8Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai8Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ不・着回数5; column=Jyotai8Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai8Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ不・着回数6; column=Jyotai8Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai9Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=障良・着回数1; column=Jyotai9Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai9Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=障良・着回数2; column=Jyotai9Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai9Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=障良・着回数3; column=Jyotai9Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai9Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=障良・着回数4; column=Jyotai9Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai9Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=障良・着回数5; column=Jyotai9Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai9Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=障良・着回数6; column=Jyotai9Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai10Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=障稍・着回数1; column=Jyotai10Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai10Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=障稍・着回数2; column=Jyotai10Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai10Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=障稍・着回数3; column=Jyotai10Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai10Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=障稍・着回数4; column=Jyotai10Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai10Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=障稍・着回数5; column=Jyotai10Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai10Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=障稍・着回数6; column=Jyotai10Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai11Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=障重・着回数1; column=Jyotai11Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai11Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=障重・着回数2; column=Jyotai11Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai11Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=障重・着回数3; column=Jyotai11Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai11Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=障重・着回数4; column=Jyotai11Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai11Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=障重・着回数5; column=Jyotai11Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai11Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=障重・着回数6; column=Jyotai11Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Jyotai12Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=障不・着回数1; column=Jyotai12Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Jyotai12Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=障不・着回数2; column=Jyotai12Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Jyotai12Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=障不・着回数3; column=Jyotai12Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Jyotai12Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=障不・着回数4; column=Jyotai12Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Jyotai12Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=障不・着回数5; column=Jyotai12Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Jyotai12Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=障不・着回数6; column=Jyotai12Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Kyori1Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数1; column=Kyori1Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Kyori1Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数2; column=Kyori1Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Kyori1Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数3; column=Kyori1Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Kyori1Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数4; column=Kyori1Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Kyori1Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数5; column=Kyori1Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Kyori1Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝16下・着回数6; column=Kyori1Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Kyori2Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数1; column=Kyori2Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Kyori2Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数2; column=Kyori2Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Kyori2Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数3; column=Kyori2Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Kyori2Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数4; column=Kyori2Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Kyori2Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数5; column=Kyori2Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Kyori2Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22下・着回数6; column=Kyori2Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Kyori3Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数1; column=Kyori3Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Kyori3Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数2; column=Kyori3Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Kyori3Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数3; column=Kyori3Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Kyori3Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数4; column=Kyori3Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Kyori3Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数5; column=Kyori3Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Kyori3Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=芝22超・着回数6; column=Kyori3Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Kyori4Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数1; column=Kyori4Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Kyori4Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数2; column=Kyori4Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Kyori4Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数3; column=Kyori4Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Kyori4Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数4; column=Kyori4Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Kyori4Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数5; column=Kyori4Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Kyori4Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ16下・着回数6; column=Kyori4Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Kyori5Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数1; column=Kyori5Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Kyori5Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数2; column=Kyori5Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Kyori5Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数3; column=Kyori5Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Kyori5Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数4; column=Kyori5Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Kyori5Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数5; column=Kyori5Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Kyori5Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22下・着回数6; column=Kyori5Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Kyori6Chakukaisu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数1; column=Kyori6Chakukaisu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=1着の回数（中央のみ）',
  `Kyori6Chakukaisu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数2; column=Kyori6Chakukaisu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=2着の回数（中央のみ）',
  `Kyori6Chakukaisu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数3; column=Kyori6Chakukaisu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=3着の回数（中央のみ）',
  `Kyori6Chakukaisu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数4; column=Kyori6Chakukaisu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=4着の回数（中央のみ）',
  `Kyori6Chakukaisu5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数5; column=Kyori6Chakukaisu5; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=5着の回数（中央のみ）',
  `Kyori6Chakukaisu6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ダ22超・着回数6; column=Kyori6Chakukaisu6; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=着外の回数（中央のみ）',
  `Kyakusitu1` varchar(3) DEFAULT NULL COMMENT '[COL] name=脚質傾向1; column=Kyakusitu1; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=逃げ/先行/差し/追込の出走レース判定カウント（中央のみ）',
  `Kyakusitu2` varchar(3) DEFAULT NULL COMMENT '[COL] name=脚質傾向2; column=Kyakusitu2; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=逃げ/先行/差し/追込の出走レース判定カウント（中央のみ）',
  `Kyakusitu3` varchar(3) DEFAULT NULL COMMENT '[COL] name=脚質傾向3; column=Kyakusitu3; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=逃げ/先行/差し/追込の出走レース判定カウント（中央のみ）',
  `Kyakusitu4` varchar(3) DEFAULT NULL COMMENT '[COL] name=脚質傾向4; column=Kyakusitu4; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=逃げ/先行/差し/追込の出走レース判定カウント（中央のみ）',
  `RaceCount` varchar(3) DEFAULT NULL COMMENT '[COL] name=登録レース数; column=RaceCount; table=N_UMA; class=蓄積系; doc=12-3-27-UMA; desc=JRA-VANに登録されている成績レース数',
  PRIMARY KEY (`KettoNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='[N] name=競走馬マスタ; table=N_UMA; class=蓄積系';
/*!40101 SET character_set_client = @saved_cs_client */;

--
