-- Table structure for table `S_BATAIJYU`
-- Table structure for table `S_BATAIJYU`
--

DROP TABLE IF EXISTS `S_BATAIJYU`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `S_BATAIJYU` (
  `RecordSpec` varchar(2) DEFAULT NULL,
  `DataKubun` varchar(1) DEFAULT NULL,
  `MakeDate` varchar(8) DEFAULT NULL,
  `Year` varchar(4) NOT NULL,
  `MonthDay` varchar(4) DEFAULT NULL,
  `JyoCD` varchar(2) NOT NULL,
  `Kaiji` varchar(2) NOT NULL,
  `Nichiji` varchar(2) NOT NULL,
  `RaceNum` varchar(2) NOT NULL,
  `HappyoTime` varchar(8) DEFAULT NULL,
  `Umaban1` varchar(2) DEFAULT NULL,
  `Bamei1` varchar(36) DEFAULT NULL,
  `BaTaijyu1` varchar(3) DEFAULT NULL,
  `ZogenFugo1` varchar(1) DEFAULT NULL,
  `ZogenSa1` varchar(3) DEFAULT NULL,
  `Umaban2` varchar(2) DEFAULT NULL,
  `Bamei2` varchar(36) DEFAULT NULL,
  `BaTaijyu2` varchar(3) DEFAULT NULL,
  `ZogenFugo2` varchar(1) DEFAULT NULL,
  `ZogenSa2` varchar(3) DEFAULT NULL,
  `Umaban3` varchar(2) DEFAULT NULL,
  `Bamei3` varchar(36) DEFAULT NULL,
  `BaTaijyu3` varchar(3) DEFAULT NULL,
  `ZogenFugo3` varchar(1) DEFAULT NULL,
  `ZogenSa3` varchar(3) DEFAULT NULL,
  `Umaban4` varchar(2) DEFAULT NULL,
  `Bamei4` varchar(36) DEFAULT NULL,
  `BaTaijyu4` varchar(3) DEFAULT NULL,
  `ZogenFugo4` varchar(1) DEFAULT NULL,
  `ZogenSa4` varchar(3) DEFAULT NULL,
  `Umaban5` varchar(2) DEFAULT NULL,
  `Bamei5` varchar(36) DEFAULT NULL,
  `BaTaijyu5` varchar(3) DEFAULT NULL,
  `ZogenFugo5` varchar(1) DEFAULT NULL,
  `ZogenSa5` varchar(3) DEFAULT NULL,
  `Umaban6` varchar(2) DEFAULT NULL,
  `Bamei6` varchar(36) DEFAULT NULL,
  `BaTaijyu6` varchar(3) DEFAULT NULL,
  `ZogenFugo6` varchar(1) DEFAULT NULL,
  `ZogenSa6` varchar(3) DEFAULT NULL,
  `Umaban7` varchar(2) DEFAULT NULL,
  `Bamei7` varchar(36) DEFAULT NULL,
  `BaTaijyu7` varchar(3) DEFAULT NULL,
  `ZogenFugo7` varchar(1) DEFAULT NULL,
  `ZogenSa7` varchar(3) DEFAULT NULL,
  `Umaban8` varchar(2) DEFAULT NULL,
  `Bamei8` varchar(36) DEFAULT NULL,
  `BaTaijyu8` varchar(3) DEFAULT NULL,
  `ZogenFugo8` varchar(1) DEFAULT NULL,
  `ZogenSa8` varchar(3) DEFAULT NULL,
  `Umaban9` varchar(2) DEFAULT NULL,
  `Bamei9` varchar(36) DEFAULT NULL,
  `BaTaijyu9` varchar(3) DEFAULT NULL,
  `ZogenFugo9` varchar(1) DEFAULT NULL,
  `ZogenSa9` varchar(3) DEFAULT NULL,
  `Umaban10` varchar(2) DEFAULT NULL,
  `Bamei10` varchar(36) DEFAULT NULL,
  `BaTaijyu10` varchar(3) DEFAULT NULL,
  `ZogenFugo10` varchar(1) DEFAULT NULL,
  `ZogenSa10` varchar(3) DEFAULT NULL,
  `Umaban11` varchar(2) DEFAULT NULL,
  `Bamei11` varchar(36) DEFAULT NULL,
  `BaTaijyu11` varchar(3) DEFAULT NULL,
  `ZogenFugo11` varchar(1) DEFAULT NULL,
  `ZogenSa11` varchar(3) DEFAULT NULL,
  `Umaban12` varchar(2) DEFAULT NULL,
  `Bamei12` varchar(36) DEFAULT NULL,
  `BaTaijyu12` varchar(3) DEFAULT NULL,
  `ZogenFugo12` varchar(1) DEFAULT NULL,
  `ZogenSa12` varchar(3) DEFAULT NULL,
  `Umaban13` varchar(2) DEFAULT NULL,
  `Bamei13` varchar(36) DEFAULT NULL,
  `BaTaijyu13` varchar(3) DEFAULT NULL,
  `ZogenFugo13` varchar(1) DEFAULT NULL,
  `ZogenSa13` varchar(3) DEFAULT NULL,
  `Umaban14` varchar(2) DEFAULT NULL,
  `Bamei14` varchar(36) DEFAULT NULL,
  `BaTaijyu14` varchar(3) DEFAULT NULL,
  `ZogenFugo14` varchar(1) DEFAULT NULL,
  `ZogenSa14` varchar(3) DEFAULT NULL,
  `Umaban15` varchar(2) DEFAULT NULL,
  `Bamei15` varchar(36) DEFAULT NULL,
  `BaTaijyu15` varchar(3) DEFAULT NULL,
  `ZogenFugo15` varchar(1) DEFAULT NULL,
  `ZogenSa15` varchar(3) DEFAULT NULL,
  `Umaban16` varchar(2) DEFAULT NULL,
  `Bamei16` varchar(36) DEFAULT NULL,
  `BaTaijyu16` varchar(3) DEFAULT NULL,
  `ZogenFugo16` varchar(1) DEFAULT NULL,
  `ZogenSa16` varchar(3) DEFAULT NULL,
  `Umaban17` varchar(2) DEFAULT NULL,
  `Bamei17` varchar(36) DEFAULT NULL,
  `BaTaijyu17` varchar(3) DEFAULT NULL,
  `ZogenFugo17` varchar(1) DEFAULT NULL,
  `ZogenSa17` varchar(3) DEFAULT NULL,
  `Umaban18` varchar(2) DEFAULT NULL,
  `Bamei18` varchar(36) DEFAULT NULL,
  `BaTaijyu18` varchar(3) DEFAULT NULL,
  `ZogenFugo18` varchar(1) DEFAULT NULL,
  `ZogenSa18` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`Year`,`JyoCD`,`Kaiji`,`Nichiji`,`RaceNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='[S] name=馬体重; table=S_BATAIJYU; class=速報系';
/*!40101 SET character_set_client = @saved_cs_client */;

--
