-- Table structure for table `S_HARAI`
-- Table structure for table `S_HARAI`
--

DROP TABLE IF EXISTS `S_HARAI`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `S_HARAI` (
  `RecordSpec` varchar(2) DEFAULT NULL COMMENT '[COL] name=レコード種別ID; column=RecordSpec; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=HRでレコード形式を識別',
  `DataKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=データ区分; column=DataKubun; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=1速報払戻確定/2成績(月)/9中止/0削除',
  `MakeDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=データ作成年月日; column=MakeDate; table=S_HARAI; class=速報系; unit=yyyymmdd; doc=12-3-05-HARAI; desc=作成日(西暦8桁)',
  `Year` varchar(4) NOT NULL COMMENT '[COL] name=開催年; column=Year; table=S_HARAI; class=速報系; unit=yyyy; doc=12-3-05-HARAI; desc=施行年',
  `MonthDay` varchar(4) NOT NULL COMMENT '[COL] name=開催月日; column=MonthDay; table=S_HARAI; class=速報系; unit=mmdd; doc=12-3-05-HARAI; desc=施行月日',
  `JyoCD` varchar(2) NOT NULL COMMENT '[COL] name=競馬場コード; column=JyoCD; table=S_HARAI; class=速報系; ref=code:2001; doc=12-3-05-HARAI; desc=施行競馬場コード',
  `Kaiji` varchar(2) NOT NULL COMMENT '[COL] name=開催回; column=Kaiji; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同年同場の開催回',
  `Nichiji` varchar(2) NOT NULL COMMENT '[COL] name=開催日目; column=Nichiji; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=開催回内の日目',
  `RaceNum` varchar(2) NOT NULL COMMENT '[COL] name=レース番号; column=RaceNum; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当レース番号',
  `TorokuTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=登録頭数; column=TorokuTosu; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=登録頭数',
  `SyussoTosu` varchar(2) DEFAULT NULL COMMENT '[COL] name=出走頭数; column=SyussoTosu; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=取消･除外反映後',
  `FuseirituFlag1` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(単勝); column=FuseirituFlag1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `FuseirituFlag2` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(複勝); column=FuseirituFlag2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `FuseirituFlag3` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(枠連); column=FuseirituFlag3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `FuseirituFlag4` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(馬連); column=FuseirituFlag4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `FuseirituFlag5` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(ワイド); column=FuseirituFlag5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `FuseirituFlag6` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(予備1); column=FuseirituFlag6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `FuseirituFlag7` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(馬単); column=FuseirituFlag7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `FuseirituFlag8` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(3連複); column=FuseirituFlag8; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `FuseirituFlag9` varchar(1) DEFAULT NULL COMMENT '[COL] name=不成立フラグ(3連単); column=FuseirituFlag9; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag1` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(単勝); column=TokubaraiFlag1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag2` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(複勝); column=TokubaraiFlag2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag3` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(枠連); column=TokubaraiFlag3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag4` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(馬連); column=TokubaraiFlag4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag5` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(ワイド); column=TokubaraiFlag5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag6` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(予備1); column=TokubaraiFlag6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag7` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(馬単); column=TokubaraiFlag7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag8` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(3連複); column=TokubaraiFlag8; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `TokubaraiFlag9` varchar(1) DEFAULT NULL COMMENT '[COL] name=特払フラグ(3連単); column=TokubaraiFlag9; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag1` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(単勝); column=HenkanFlag1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag2` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(複勝); column=HenkanFlag2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag3` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(枠連); column=HenkanFlag3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag4` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(馬連); column=HenkanFlag4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag5` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(ワイド); column=HenkanFlag5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag6` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(予備1); column=HenkanFlag6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag7` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(馬単); column=HenkanFlag7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag8` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(3連複); column=HenkanFlag8; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanFlag9` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還フラグ(3連単); column=HenkanFlag9; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0無し/1あり',
  `HenkanUma1` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報1; column=HenkanUma1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma2` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報2; column=HenkanUma2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma3` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報3; column=HenkanUma3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma4` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報4; column=HenkanUma4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma5` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報5; column=HenkanUma5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma6` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報6; column=HenkanUma6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma7` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報7; column=HenkanUma7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma8` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報8; column=HenkanUma8; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma9` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報9; column=HenkanUma9; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma10` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報10; column=HenkanUma10; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma11` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報11; column=HenkanUma11; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma12` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報12; column=HenkanUma12; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma13` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報13; column=HenkanUma13; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma14` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報14; column=HenkanUma14; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma15` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報15; column=HenkanUma15; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma16` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報16; column=HenkanUma16; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma17` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報17; column=HenkanUma17; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma18` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報18; column=HenkanUma18; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma19` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報19; column=HenkanUma19; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma20` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報20; column=HenkanUma20; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma21` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報21; column=HenkanUma21; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma22` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報22; column=HenkanUma22; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma23` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報23; column=HenkanUma23; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma24` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報24; column=HenkanUma24; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma25` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報25; column=HenkanUma25; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma26` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報26; column=HenkanUma26; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma27` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報27; column=HenkanUma27; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanUma28` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還馬番情報28; column=HenkanUma28; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanWaku1` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報1; column=HenkanWaku1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanWaku2` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報2; column=HenkanWaku2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanWaku3` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報3; column=HenkanWaku3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanWaku4` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報4; column=HenkanWaku4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanWaku5` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報5; column=HenkanWaku5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanWaku6` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報6; column=HenkanWaku6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanWaku7` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報7; column=HenkanWaku7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanWaku8` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還枠番情報8; column=HenkanWaku8; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=該当ビット=1',
  `HenkanDoWaku1` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報1; column=HenkanDoWaku1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同枠のみ返還：該当ビット=1',
  `HenkanDoWaku2` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報2; column=HenkanDoWaku2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同枠のみ返還：該当ビット=1',
  `HenkanDoWaku3` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報3; column=HenkanDoWaku3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同枠のみ返還：該当ビット=1',
  `HenkanDoWaku4` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報4; column=HenkanDoWaku4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同枠のみ返還：該当ビット=1',
  `HenkanDoWaku5` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報5; column=HenkanDoWaku5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同枠のみ返還：該当ビット=1',
  `HenkanDoWaku6` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報6; column=HenkanDoWaku6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同枠のみ返還：該当ビット=1',
  `HenkanDoWaku7` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報7; column=HenkanDoWaku7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同枠のみ返還：該当ビット=1',
  `HenkanDoWaku8` varchar(1) DEFAULT NULL COMMENT '[COL] name=返還同枠情報8; column=HenkanDoWaku8; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=同枠のみ返還：該当ビット=1',
  `PayTansyoUmaban1` varchar(2) DEFAULT NULL COMMENT '[COL] name=単勝的中馬番1; column=PayTansyoUmaban1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayTansyoPay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=単勝払戻金1; column=PayTansyoPay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayTansyoNinki1` varchar(2) DEFAULT NULL COMMENT '[COL] name=単勝人気順1; column=PayTansyoNinki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayTansyoUmaban2` varchar(2) DEFAULT NULL COMMENT '[COL] name=単勝的中馬番2; column=PayTansyoUmaban2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayTansyoPay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=単勝払戻金2; column=PayTansyoPay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayTansyoNinki2` varchar(2) DEFAULT NULL COMMENT '[COL] name=単勝人気順2; column=PayTansyoNinki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayTansyoUmaban3` varchar(2) DEFAULT NULL COMMENT '[COL] name=単勝的中馬番3; column=PayTansyoUmaban3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayTansyoPay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=単勝払戻金3; column=PayTansyoPay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayTansyoNinki3` varchar(2) DEFAULT NULL COMMENT '[COL] name=単勝人気順3; column=PayTansyoNinki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoUmaban1` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝的中馬番1; column=PayFukusyoUmaban1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayFukusyoPay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=複勝払戻金1; column=PayFukusyoPay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoNinki1` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝人気順1; column=PayFukusyoNinki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoUmaban2` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝的中馬番2; column=PayFukusyoUmaban2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayFukusyoPay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=複勝払戻金2; column=PayFukusyoPay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoNinki2` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝人気順2; column=PayFukusyoNinki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoUmaban3` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝的中馬番3; column=PayFukusyoUmaban3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayFukusyoPay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=複勝払戻金3; column=PayFukusyoPay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoNinki3` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝人気順3; column=PayFukusyoNinki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoUmaban4` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝的中馬番4; column=PayFukusyoUmaban4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayFukusyoPay4` varchar(9) DEFAULT NULL COMMENT '[COL] name=複勝払戻金4; column=PayFukusyoPay4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoNinki4` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝人気順4; column=PayFukusyoNinki4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoUmaban5` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝的中馬番5; column=PayFukusyoUmaban5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayFukusyoPay5` varchar(9) DEFAULT NULL COMMENT '[COL] name=複勝払戻金5; column=PayFukusyoPay5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayFukusyoNinki5` varchar(2) DEFAULT NULL COMMENT '[COL] name=複勝人気順5; column=PayFukusyoNinki5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWakurenKumi1` varchar(2) DEFAULT NULL COMMENT '[COL] name=枠連的中枠番1; column=PayWakurenKumi1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayWakurenPay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=枠連払戻金1; column=PayWakurenPay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWakurenNinki1` varchar(2) DEFAULT NULL COMMENT '[COL] name=枠連人気順1; column=PayWakurenNinki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWakurenKumi2` varchar(2) DEFAULT NULL COMMENT '[COL] name=枠連的中枠番2; column=PayWakurenKumi2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayWakurenPay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=枠連払戻金2; column=PayWakurenPay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWakurenNinki2` varchar(2) DEFAULT NULL COMMENT '[COL] name=枠連人気順2; column=PayWakurenNinki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWakurenKumi3` varchar(2) DEFAULT NULL COMMENT '[COL] name=枠連的中枠番3; column=PayWakurenKumi3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=00:発売無/特払/不成立',
  `PayWakurenPay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=枠連払戻金3; column=PayWakurenPay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWakurenNinki3` varchar(2) DEFAULT NULL COMMENT '[COL] name=枠連人気順3; column=PayWakurenNinki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmarenKumi1` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬連的中馬番組合1; column=PayUmarenKumi1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmarenPay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬連払戻金1; column=PayUmarenPay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmarenNinki1` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬連人気順1; column=PayUmarenNinki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmarenKumi2` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬連的中馬番組合2; column=PayUmarenKumi2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmarenPay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬連払戻金2; column=PayUmarenPay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmarenNinki2` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬連人気順2; column=PayUmarenNinki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmarenKumi3` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬連的中馬番組合3; column=PayUmarenKumi3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmarenPay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬連払戻金3; column=PayUmarenPay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmarenNinki3` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬連人気順3; column=PayUmarenNinki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideKumi1` varchar(4) DEFAULT NULL COMMENT '[COL] name=ワイド的中馬番組合1; column=PayWideKumi1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayWidePay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=ワイド払戻金1; column=PayWidePay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideNinki1` varchar(3) DEFAULT NULL COMMENT '[COL] name=ワイド人気順1; column=PayWideNinki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideKumi2` varchar(4) DEFAULT NULL COMMENT '[COL] name=ワイド的中馬番組合2; column=PayWideKumi2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayWidePay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=ワイド払戻金2; column=PayWidePay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideNinki2` varchar(3) DEFAULT NULL COMMENT '[COL] name=ワイド人気順2; column=PayWideNinki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideKumi3` varchar(4) DEFAULT NULL COMMENT '[COL] name=ワイド的中馬番組合3; column=PayWideKumi3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayWidePay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=ワイド払戻金3; column=PayWidePay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideNinki3` varchar(3) DEFAULT NULL COMMENT '[COL] name=ワイド人気順3; column=PayWideNinki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideKumi4` varchar(4) DEFAULT NULL COMMENT '[COL] name=ワイド的中馬番組合4; column=PayWideKumi4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayWidePay4` varchar(9) DEFAULT NULL COMMENT '[COL] name=ワイド払戻金4; column=PayWidePay4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideNinki4` varchar(3) DEFAULT NULL COMMENT '[COL] name=ワイド人気順4; column=PayWideNinki4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideKumi5` varchar(4) DEFAULT NULL COMMENT '[COL] name=ワイド的中馬番組合5; column=PayWideKumi5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayWidePay5` varchar(9) DEFAULT NULL COMMENT '[COL] name=ワイド払戻金5; column=PayWidePay5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideNinki5` varchar(3) DEFAULT NULL COMMENT '[COL] name=ワイド人気順5; column=PayWideNinki5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideKumi6` varchar(4) DEFAULT NULL COMMENT '[COL] name=ワイド的中馬番組合6; column=PayWideKumi6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayWidePay6` varchar(9) DEFAULT NULL COMMENT '[COL] name=ワイド払戻金6; column=PayWidePay6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideNinki6` varchar(3) DEFAULT NULL COMMENT '[COL] name=ワイド人気順6; column=PayWideNinki6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideKumi7` varchar(4) DEFAULT NULL COMMENT '[COL] name=ワイド的中馬番組合7; column=PayWideKumi7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayWidePay7` varchar(9) DEFAULT NULL COMMENT '[COL] name=ワイド払戻金7; column=PayWidePay7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayWideNinki7` varchar(3) DEFAULT NULL COMMENT '[COL] name=ワイド人気順7; column=PayWideNinki7; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Kumi1` varchar(4) DEFAULT NULL COMMENT '[COL] name=予備払戻1_組番1; column=PayReserved1Kumi1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Pay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=予備払戻1_払戻金1; column=PayReserved1Pay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Ninki1` varchar(3) DEFAULT NULL COMMENT '[COL] name=予備払戻1_人気順1; column=PayReserved1Ninki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Kumi2` varchar(4) DEFAULT NULL COMMENT '[COL] name=予備払戻1_組番2; column=PayReserved1Kumi2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Pay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=予備払戻1_払戻金2; column=PayReserved1Pay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Ninki2` varchar(3) DEFAULT NULL COMMENT '[COL] name=予備払戻1_人気順2; column=PayReserved1Ninki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Kumi3` varchar(4) DEFAULT NULL COMMENT '[COL] name=予備払戻1_組番3; column=PayReserved1Kumi3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Pay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=予備払戻1_払戻金3; column=PayReserved1Pay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayReserved1Ninki3` varchar(3) DEFAULT NULL COMMENT '[COL] name=予備払戻1_人気順3; column=PayReserved1Ninki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanKumi1` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬単的中馬番組合1; column=PayUmatanKumi1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmatanPay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬単払戻金1; column=PayUmatanPay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanNinki1` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬単人気順1; column=PayUmatanNinki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanKumi2` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬単的中馬番組合2; column=PayUmatanKumi2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmatanPay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬単払戻金2; column=PayUmatanPay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanNinki2` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬単人気順2; column=PayUmatanNinki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanKumi3` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬単的中馬番組合3; column=PayUmatanKumi3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmatanPay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬単払戻金3; column=PayUmatanPay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanNinki3` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬単人気順3; column=PayUmatanNinki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanKumi4` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬単的中馬番組合4; column=PayUmatanKumi4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmatanPay4` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬単払戻金4; column=PayUmatanPay4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanNinki4` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬単人気順4; column=PayUmatanNinki4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanKumi5` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬単的中馬番組合5; column=PayUmatanKumi5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmatanPay5` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬単払戻金5; column=PayUmatanPay5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanNinki5` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬単人気順5; column=PayUmatanNinki5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanKumi6` varchar(4) DEFAULT NULL COMMENT '[COL] name=馬単的中馬番組合6; column=PayUmatanKumi6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=0000:発売無/特払/不成立',
  `PayUmatanPay6` varchar(9) DEFAULT NULL COMMENT '[COL] name=馬単払戻金6; column=PayUmatanPay6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PayUmatanNinki6` varchar(3) DEFAULT NULL COMMENT '[COL] name=馬単人気順6; column=PayUmatanNinki6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrenpukuKumi1` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連複的中馬番組合1; column=PaySanrenpukuKumi1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrenpukuPay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連複払戻金1; column=PaySanrenpukuPay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrenpukuNinki1` varchar(3) DEFAULT NULL COMMENT '[COL] name=3連複人気順1; column=PaySanrenpukuNinki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrenpukuKumi2` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連複的中馬番組合2; column=PaySanrenpukuKumi2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrenpukuPay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連複払戻金2; column=PaySanrenpukuPay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrenpukuNinki2` varchar(3) DEFAULT NULL COMMENT '[COL] name=3連複人気順2; column=PaySanrenpukuNinki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrenpukuKumi3` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連複的中馬番組合3; column=PaySanrenpukuKumi3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrenpukuPay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連複払戻金3; column=PaySanrenpukuPay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrenpukuNinki3` varchar(3) DEFAULT NULL COMMENT '[COL] name=3連複人気順3; column=PaySanrenpukuNinki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanKumi1` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連単的中馬番組合1; column=PaySanrentanKumi1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrentanPay1` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連単払戻金1; column=PaySanrentanPay1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanNinki1` varchar(4) DEFAULT NULL COMMENT '[COL] name=3連単人気順1; column=PaySanrentanNinki1; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanKumi2` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連単的中馬番組合2; column=PaySanrentanKumi2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrentanPay2` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連単払戻金2; column=PaySanrentanPay2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanNinki2` varchar(4) DEFAULT NULL COMMENT '[COL] name=3連単人気順2; column=PaySanrentanNinki2; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanKumi3` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連単的中馬番組合3; column=PaySanrentanKumi3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrentanPay3` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連単払戻金3; column=PaySanrentanPay3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanNinki3` varchar(4) DEFAULT NULL COMMENT '[COL] name=3連単人気順3; column=PaySanrentanNinki3; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanKumi4` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連単的中馬番組合4; column=PaySanrentanKumi4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrentanPay4` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連単払戻金4; column=PaySanrentanPay4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanNinki4` varchar(4) DEFAULT NULL COMMENT '[COL] name=3連単人気順4; column=PaySanrentanNinki4; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanKumi5` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連単的中馬番組合5; column=PaySanrentanKumi5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrentanPay5` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連単払戻金5; column=PaySanrentanPay5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanNinki5` varchar(4) DEFAULT NULL COMMENT '[COL] name=3連単人気順5; column=PaySanrentanNinki5; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanKumi6` varchar(6) DEFAULT NULL COMMENT '[COL] name=3連単的中馬番組合6; column=PaySanrentanKumi6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI; desc=000000:発売無/特払/不成立',
  `PaySanrentanPay6` varchar(9) DEFAULT NULL COMMENT '[COL] name=3連単払戻金6; column=PaySanrentanPay6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  `PaySanrentanNinki6` varchar(4) DEFAULT NULL COMMENT '[COL] name=3連単人気順6; column=PaySanrentanNinki6; table=S_HARAI; class=速報系; doc=12-3-05-HARAI',
  PRIMARY KEY (`Year`,`MonthDay`,`JyoCD`,`Kaiji`,`Nichiji`,`RaceNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='[S] name=払戻; table=S_HARAI; class=速報系';
/*!40101 SET character_set_client = @saved_cs_client */;

--
