-- Table structure for table `S_MINING`
-- Table structure for table `S_MINING`
--

DROP TABLE IF EXISTS `S_MINING`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `S_MINING` (
  `RecordSpec` varchar(2) DEFAULT NULL COMMENT '[COL] name=レコード種別ID; column=RecordSpec; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=DMでレコード形式を識別',
  `DataKubun` varchar(1) DEFAULT NULL COMMENT '[COL] name=データ区分; column=DataKubun; table=S_MINING; class=速報系; doc=12-3-44-MINING; vals=1:前日予想(出馬発表後) 2:当日予想(天候馬場発表後) 3:直前予想(馬体重発表後)',
  `MakeDate` varchar(8) DEFAULT NULL COMMENT '[COL] name=データ作成年月日; column=MakeDate; table=S_MINING; class=速報系; unit=yyyymmdd; doc=12-3-44-MINING',
  `Year` varchar(4) NOT NULL COMMENT '[COL] name=開催年; column=Year; table=S_MINING; class=速報系; unit=yyyy; key=○; doc=12-3-44-MINING',
  `MonthDay` varchar(4) DEFAULT NULL COMMENT '[COL] name=開催月日; column=MonthDay; table=S_MINING; class=速報系; unit=mmdd; key=○; doc=12-3-44-MINING',
  `JyoCD` varchar(2) NOT NULL COMMENT '[COL] name=競馬場コード; column=JyoCD; table=S_MINING; class=速報系; ref=code:2001; key=○; doc=12-3-44-MINING',
  `Kaiji` varchar(2) NOT NULL COMMENT '[COL] name=開催回; column=Kaiji; table=S_MINING; class=速報系; key=○; doc=12-3-44-MINING; desc=同年同場での第N回',
  `Nichiji` varchar(2) NOT NULL COMMENT '[COL] name=開催日目; column=Nichiji; table=S_MINING; class=速報系; key=○; doc=12-3-44-MINING; desc=開催回内のN日目',
  `RaceNum` varchar(2) NOT NULL COMMENT '[COL] name=レース番号; column=RaceNum; table=S_MINING; class=速報系; key=○; doc=12-3-44-MINING',
  `MakeHM` varchar(4) DEFAULT NULL COMMENT '[COL] name=データ作成時分; column=MakeHM; table=S_MINING; class=速報系; unit=hhmm; doc=12-3-44-MINING; desc=時分各2桁',
  `Umaban1` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番1; column=Umaban1; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime1` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム1; column=DMTime1; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP1` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+1; column=DMGosaP1; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM1` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-1; column=DMGosaM1; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban2` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番2; column=Umaban2; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime2` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム2; column=DMTime2; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP2` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+2; column=DMGosaP2; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM2` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-2; column=DMGosaM2; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban3` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番3; column=Umaban3; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime3` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム3; column=DMTime3; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP3` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+3; column=DMGosaP3; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM3` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-3; column=DMGosaM3; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban4` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番4; column=Umaban4; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime4` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム4; column=DMTime4; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP4` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+4; column=DMGosaP4; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM4` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-4; column=DMGosaM4; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban5` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番5; column=Umaban5; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime5` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム5; column=DMTime5; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP5` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+5; column=DMGosaP5; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM5` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-5; column=DMGosaM5; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban6` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番6; column=Umaban6; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime6` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム6; column=DMTime6; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP6` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+6; column=DMGosaP6; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM6` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-6; column=DMGosaM6; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban7` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番7; column=Umaban7; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime7` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム7; column=DMTime7; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP7` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+7; column=DMGosaP7; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM7` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-7; column=DMGosaM7; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban8` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番8; column=Umaban8; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime8` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム8; column=DMTime8; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP8` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+8; column=DMGosaP8; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM8` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-8; column=DMGosaM8; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban9` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番9; column=Umaban9; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime9` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム9; column=DMTime9; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP9` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+9; column=DMGosaP9; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM9` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-9; column=DMGosaM9; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban10` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番10; column=Umaban10; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime10` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム10; column=DMTime10; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP10` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+10; column=DMGosaP10; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM10` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-10; column=DMGosaM10; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban11` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番11; column=Umaban11; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime11` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム11; column=DMTime11; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP11` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+11; column=DMGosaP11; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM11` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-11; column=DMGosaM11; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban12` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番12; column=Umaban12; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime12` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム12; column=DMTime12; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP12` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+12; column=DMGosaP12; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM12` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-12; column=DMGosaM12; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban13` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番13; column=Umaban13; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime13` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム13; column=DMTime13; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP13` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+13; column=DMGosaP13; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM13` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-13; column=DMGosaM13; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban14` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番14; column=Umaban14; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime14` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム14; column=DMTime14; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP14` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+14; column=DMGosaP14; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM14` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-14; column=DMGosaM14; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban15` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番15; column=Umaban15; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime15` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム15; column=DMTime15; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP15` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+15; column=DMGosaP15; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM15` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-15; column=DMGosaM15; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban16` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番16; column=Umaban16; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime16` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム16; column=DMTime16; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP16` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+16; column=DMGosaP16; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM16` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-16; column=DMGosaM16; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban17` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番17; column=Umaban17; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime17` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム17; column=DMTime17; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP17` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+17; column=DMGosaP17; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM17` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-17; column=DMGosaM17; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  `Umaban18` varchar(2) DEFAULT NULL COMMENT '[COL] name=馬番18; column=Umaban18; table=S_MINING; class=速報系; doc=12-3-44-MINING; desc=01～18を設定',
  `DMTime18` varchar(5) DEFAULT NULL COMMENT '[COL] name=予想走破タイム18; column=DMTime18; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=9分99秒99',
  `DMGosaP18` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)+18; column=DMGosaP18; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=＋方向(予想より早い; 予想タイムからマイナス)',
  `DMGosaM18` varchar(4) DEFAULT NULL COMMENT '[COL] name=予想誤差(信頼度)-18; column=DMGosaM18; table=S_MINING; class=速報系; doc=12-3-44-MINING; format=99秒99; desc=－方向(予想より遅い; 予想タイムにプラス)',
  PRIMARY KEY (`Year`,`JyoCD`,`Kaiji`,`Nichiji`,`RaceNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='[S] name=タイム型データマイニング予想; table=S_MINING; class=速報系';
/*!40101 SET character_set_client = @saved_cs_client */;

--
